INSERT INTO Team(name, country, region) VALUES ("Loveless", "United Arab Emirates", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Let's Do It", "Poland", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Gears of Destruction", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Team DileCom", "Peru", "South America");
INSERT INTO Team(name, country, region) VALUES ("Team Liquid", "Netherlands", "Europe");
INSERT INTO Team(name, country, region) VALUES ("FDL", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("Resurgence", "Singapore", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Team FanTuan", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Scratch the Surface", "Iraq", "Asia");
INSERT INTO Team(name, country, region) VALUES ("J.Storm", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("Cloud9", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("Thunderbirds", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("HAPPY GUYS", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("MidOrFeed", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Team OD", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Mineski", "Philippines", "Asia");
INSERT INTO Team(name, country, region) VALUES ("paiN X", "Brazil", "South America");
INSERT INTO Team(name, country, region) VALUES ("Sweden", "Sweden", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Prodota Gaming", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Team VGJ", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Kaipi", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Danish Bears", "Denmark", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Bravado Gaming", "South Africa", "Africa");
INSERT INTO Team(name, country, region) VALUES ("compLexity Gaming", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("PiTER", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("4Hate", "Singapore", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Union Gaming BO", "Bolivia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Wombat Gaming", "Germany", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Team Serenity", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("No Logic Gaming", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Moogle", "Singapore", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Newbee", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Intelligence Quotient", "Cambodia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Art of Execution", "Syria", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Da Teletubbies", "Australia", "Australia");
INSERT INTO Team(name, country, region) VALUES ("Denmark", "Denmark", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Monkey Freedom Fighters", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Orcus", "Jordan", "Asia");
INSERT INTO Team(name, country, region) VALUES ("United We Stand", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("HappyFeet", "Philippines", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Rock.Y", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("FlyToMoon", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Signify", "India", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Entity Gaming", "India", "Asia");
INSERT INTO Team(name, country, region) VALUES ("We Are Young", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("NecroRaisers", "Czech Republic", "Europe");
INSERT INTO Team(name, country, region) VALUES ("ANIMA.APACHE", "Russia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("ROOT Gaming", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("Top Team", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Zero Hoots Given", "Germany", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Excellent!", "France", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Immortals", "South Korea", "Asia");
INSERT INTO Team(name, country, region) VALUES ("URUK-HIGH", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Team Admiral", "Philippines", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Gersenz", "Mongolia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Void Boys", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("CDEC Avenger", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("United Kingdom", "United Kingdom", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Ten Twenty", "Singapore", "Asia");
INSERT INTO Team(name, country, region) VALUES ("4 Clover & Lepricon", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("STARK", "Germany", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Team Redemption", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Wings Gaming", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("EHOME.Keen", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Newbee Young", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Team Lithium", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Young Minds", "Philippines", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Team FIRE", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("Avalon Club", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("WU TANG", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("HellRaisers", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Clutch Gamers", "Philippines", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Fantastic Five", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Newteam123123", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Serbia", "Serbia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("5eva", "Singapore", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Raze", "Tunisia", "Africa");
INSERT INTO Team(name, country, region) VALUES ("Kings", "Iraq", "Asia");
INSERT INTO Team(name, country, region) VALUES ("ScaryFaceZ", "Ukraine", "Europe");
INSERT INTO Team(name, country, region) VALUES ("iClen", "Australia", "Australia");
INSERT INTO Team(name, country, region) VALUES ("Team 5ive", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Train your Brain", "Tunisia", "Africa");
INSERT INTO Team(name, country, region) VALUES ("MAX.X", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Digital Chaos", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("Team MAX", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "woof", "Netherlands", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "We Say NO!", "Sri Lanka", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Execration", "Philippines", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Psuedo Gaming", "Jordan", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "No Diggity", "", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Dream Gaming", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Vanguards", "Iran", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Midas Club Elite", "Brazil", "South America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Can't Say Wips", "Australia", "Australia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "EVOS Esports", "Indonesia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "TNC Predator", "Philippines", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Quid Pro Quo", "Philippines", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "FATE eSports", "Jordan", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "White Rabbit Gaming", "South Africa", "Africa");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Royal Never Give Up", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Spirit", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "LGD Gaming", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Germany", "Germany", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Royal Bandits", "Turkey", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "TongFu", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Victory O Lord", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Underdogs", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "T Show", "Brazil", "South America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Ultima_Thule", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Burden United", "", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "F.R.I.E.N.D.S.", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Rex Regum QEON", "Indonesia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Newbee.M", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "paiN Gaming", "Brazil", "South America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Ad Finem", "Greece", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Finland", "Finland", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Butterfly Effect", "Spain", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "PRIES", "", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Malaysia", "Malaysia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Gambit Esports", "Russa", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team X-BET", "", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "MOL", "Mongolia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Hashtag?.DOTA", "Thailand", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Longwan", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Elements One", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "SFTe-sports", "Russa", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Keen Gaming", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "BendOver", "Egypt", "Africa");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "White Fries Gaming", "Malaysia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "NA Rejects", "USA", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Insane Buster", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "SG e-sports", "Brazil", "South America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Natus Vincere", "Ukraine", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Next Generation", "Vietnam", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Vega Squadron", "", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Five Libyans", "Libya", "Africa");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Life Breake", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Dogs Dota", "Jordan", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Tangos", "Sweden", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "VINCE TE IPSUM", "Brazil", "South America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "CIS Rejects", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "MVP HOT6ix", "South Korea", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Elite Wolves", "Peru", "South America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Russia", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "TPB", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "VGJ.Thunder", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Aster", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "For The Dream", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team eHug", "USA", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Peru", "Peru", "South America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Elements Pro", "Serbia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "CDEC Youth", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Faceless", "Singapore", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Rebirth eSports", "Chile", "South America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "KSY", "Australia", "Australia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Power Gaming", "Malaysia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Hippomaniacs", "Czech Republic", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Without Problems", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "MVP Aegis", "South Korea", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Evil Geniuses", "USA", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "G Guard Esports", "Malaysia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Infamous", "Peru", "South America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Baskonia eSports", "Spain", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "BPlease 420", "Morocco", "Africa");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Odium", "Ukraine", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Tigers", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Smash", "Saudi Arabia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "OpTic Gaming", "USA", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "AntiHype", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "2K Players", "United Arab Emirates", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Flash", "Malaysia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "LaFlamme", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Power Rangers", "Belarus", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Slayers", "Singapore", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Josskie", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "ROOONS", "Canada", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "madjor atendari", "Bulgaria", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Brave Heart", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Geek Fam", "Malaysia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Rock", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "HOMETE", "South Korea", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "KnownFor", "Egypt", "Africa");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Leviathan", "USA", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "PSG.LGD", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "DeToNator", "Philippines", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "818 Esports", "Malaysia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Alliance", "Sweden", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Vici Gaming Reborn", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Fire Dragoon", "Malaysia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Secret", "", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Gremory Household", "Saudi Arabia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Wheel Whreck", "USA", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "FTD club C", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Basically Unknown", "Sweden", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "ANT E-Sports", "Turkey", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Forward Gaming", "USA", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "NoFear", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Big and Black", "Australia", "Australia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "TNC Pro Team", "Philippines", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Archon", "USA", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Hellas", "Greece", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Nemiga Gaming", "Belarus", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "CDEC Gaming", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "4 Anchors + SC", "Finland", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Natural 9", "Australia", "Australia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Doteri dva", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "MOBILE GIRL", "Malaysia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Golden Boys", "Peru", "South America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "UAshki", "Ukraine", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Zeta Pegasi", "Norway", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Orange.Taring", "Malaysia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "XENEX Gaming", "United Kingdom", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "VGJ.Storm", "USA", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team NP", "USA", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "NoLifer5.Reborn", "Kyrgyzstan", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Netherlands", "Netherlands", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "YAROST TOPORA", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Random", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Mad Dogs Team", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "LVLUP", "", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Lebanon", "Lebanon", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Not Today", "Peru", "South America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "MAX.Y", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Kingao+4", "Brazil", "South America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Virtus.pro", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Lemondogs", "Sweden", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Mamas Boys", "", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "DVK", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "No Biggie", "Sweden", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Nation", "Australia", "Australia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Invictus Gaming", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team SatuDuaTiga", "Malaysia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Noobies in Team", "Morocco", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "InfinityVN", "Vietnam", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Kazakhstan", "Kazakhstan", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Electrify", "Singapore", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Comanche", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Fnatic", "Malaysia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Rave", "Philippines", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Bracerking", "Malaysia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Game of Throwz", "Kuwait", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Hollow", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Invasion e-Sports", "Malaysia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "EHOME.Luminous", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "NiceOne", "Kazakhstan", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Unknown", "Peru", "South America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Ne RusЬ", "Ukraine", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Unchained Esports", "", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Albatross", "Poland", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "The Imperial", "Denmark", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team YP", "USA", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Planet Dog", "", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Winstrike Team", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "MVP Phoenix", "South Korea", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Balkan Bears", "", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Vici Gaming Potential", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Romania", "Romania", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Terror Blade !!", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Paragon eSports", "Belarus", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Singularity", "", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "NoPangolier", "", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "DUOBAO", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Learn2Gank", "Mexico", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "RedBear", "Malaysia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Underminer", "Malaysia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "iG Vitality", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Planet Odd", "USA", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "FCDB Esports", "Belarus", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "HyperGloryTeam", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Vultur", "Argentina", "South America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Volta7", "Ecuador", "South America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "ALPHA Red", "Thailand", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Thunder Awaken", "Peru", "South America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "mousesports", "Greece", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team HighGround", "Malaysia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "ALTERNATE aTTaX", "Poland", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Dark Passage", "Turkey", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "PG.Barracx", "Indonesia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Tangerine", "Malaysia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Virtus.pro Polar", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Effect", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "G.star", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Empire", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Espada", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Slice N' Dice", "Egypt", "Africa");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Ukraine", "Ukraine", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "ferzee", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Summer's Rift", "USA", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Escape Gaming", "", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Big God", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Kabal Gaming", "Turkmenistan", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "LV Gaming", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "EHOME.X", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Que La Famille", "France", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "TongFu.WanZhou", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Vici Gaming", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Mineski.Sports5", "Philippines", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "ZOKEN GAMING", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "The Final Tribe", "Sweden", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Eximious Esports", "Pakistan", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "DUOBAO Young", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Seventh Heaven", "Australia", "Australia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Kinguin", "Poland", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "PENTA Sports", "Europe", "");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "The Mongolz", "Mongolia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Signature.Trust", "Thailand", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "iDeal eSports", "Thailand", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Arcade.PowerRangers", "Belarus", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "London Conspiracy", "Denmark", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "(monkey) Business", "", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Sacred", "Peru", "South America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Game-Life Balance", "Czech Republic", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team One Ecuador", "Ecuador", "South America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "OG", "", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "MVP Revolution", "Kyrgyzstan", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "90s Gaming", "Malaysia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "EHOME", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team DK", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Aboshamalah", "Jordan", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "To.be.or.not.to.be", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Danish Dynamite", "Denmark", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Dad is Proud", "Algeria", "Africa");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Thunderobot Gaming", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Ice", "", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Azure esports", "Hong Kong", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "People", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Horde", "Sweden", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "ZERO ONE", "Kazakhstan", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "BOOM ID", "Singapore", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "WarriorsGaming.Unity", "Malaysia", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Ignore Ochir", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Play 4 Fun", "Canada", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Flipsid3 Tactics", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Energy Pacemaker", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "mYinsanity", "", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Immortal Magneto", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Anime", "Lebanon", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Speed Gaming.cn", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Aggressive 5", "India", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "s1 Lykos", "Philippines", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Ninjas in Pyjamas", "Sweden", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "LGD.Forever Young", "China", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Monsters Have Hearts", "Algeria", "Africa");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "PUB PLAYERS", "Turkey", "Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Tinker", "", "Europe");
gameId, 1, 