INSERT INTO Team(gameId, name, country, region) VALUES (2, "MIBR", "United States Brazil", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Astralis", "Denmark", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "BIG", "Germany", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "North", "Denmark", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "NRG Esports", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Ghost Gaming", "United States Canada", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Team Liquid", "Netherlands North America", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Ninjas in Pyjamas", "Sweden", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "AVANGAR", "Kazakhstan", "CIS");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "FaZe Clan", "United States Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "5Power Gaming", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "mousesports", "Germany Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Fnatic", "United Kingdom Sweden", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Gambit Esports", "Russia", "CIS");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "ENCE eSports", "Finland", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Cloud9", "United States Europe", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Vega Squadron", "Russia", "CIS");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "OpTic Gaming", "United States Denmark", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "SK Gaming", "Germany", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Virtus.pro", "Russia Poland", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Space Soldiers", "Turkey", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Team One", "Brazil", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Immortals", "United States Brazil", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Heroic", "Denmark", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Team Russia", "Russia", "CIS");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "HellRaisers", "Ukraine Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Misfits Gaming", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "G2 Esports", "Spain France", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "GODSENT", "Sweden", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Renegades", "United States Australia", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Dobry&Gaming", "Poland", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Team Kinguin", "Poland", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Team Envy", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Luminosity Gaming", "Canada Brazil", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Team SoloMid", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Tempo Storm", "United States Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Titan", "Singapore France", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Counter Logic Gaming", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Dignitas", "United Kingdom United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "GPlay.bg", "Bulgaria", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Team Sweden", "Sweden", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Team France", "France", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "3DMAX", "France", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Team Poland", "Poland", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Copenhagen Wolves", "Denmark", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Keyd Stars", "Brazil", "South America");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "FlipSid3 Tactics", "United States CIS", "CIS");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "United5", "USA", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Team LDLC", "France", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "VeryGames", "France", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Clan-Mystik", "France", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Epsilon eSports", "Belgium Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "iBUYPOWER", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "myXMG", "Norway Denmark", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "LGB eSports", "Norway", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "compLexity Gaming", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "über G33KZ", "Denmark", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Lemondogs", "Sweden", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Denial eSports", "United States Europe", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Astana Dragons", "Kazakhstan", "CIS");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Universal Soldiers", "Poland", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Absolute Legends", "Belgium Turkey", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "n!faculty", "Germany", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "ESC Gaming", "Germany", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Moscow Five", "Russia", "CIS");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Area 51 Gaming", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "mousesports", "Germany Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Oslo Lions", "Norway", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Quantic Gaming", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Team Dynamic", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Team Curse", "United States", "North America");
