SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch World Cup 2018" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Canada" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 16000.0);
SELECT id INTO @teamId FROM Team WHERE name = "China" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 16000.0);
SELECT id INTO @teamId FROM Team WHERE name = "United Kingdom" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 16000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch League - Inaugural Season Playoffs" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "London Spitfire" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 1000000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Philadelphia Fusion" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 400000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Los Angeles Valiant" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "New York Excelsior" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 100000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Premier Series 2017 - Grand Finals" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Miraculous Youngster" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 60690.0);
SELECT id INTO @teamId FROM Team WHERE name = "Miracle Team One" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Vici Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15172.0);
SELECT id INTO @teamId FROM Team WHERE name = "1246" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 30345.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch World Cup 2017" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "South Korea" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 9000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Canada" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 9000.0);
SELECT id INTO @teamId FROM Team WHERE name = "France" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 9000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Sweden" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 9000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Pacific Championship 2017 - Season 2" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Ardeont" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 99320.0);
SELECT id INTO @teamId FROM Team WHERE name = "Flash Wolves" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 49660.0);
SELECT id INTO @teamId FROM Team WHERE name = "Hong Kong Attitude" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 26489.0);
SELECT id INTO @teamId FROM Team WHERE name = "Blank Esports" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 33107.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Premier Series 2017 - Summer" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Miraculous Youngster" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 45518.0);
SELECT id INTO @teamId FROM Team WHERE name = "Vici Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 22759.0);
SELECT id INTO @teamId FROM Team WHERE name = "Miracle Team One" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15172.0);
SELECT id INTO @teamId FROM Team WHERE name = "LGD Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 15172.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "APAC Premier 2017" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "GC Busan" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 105693.0);
SELECT id INTO @teamId FROM Team WHERE name = "Miraculous Youngster" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 18117.0);
SELECT id INTO @teamId FROM Team WHERE name = "RunAway" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 45294.0);
SELECT id INTO @teamId FROM Team WHERE name = "Afreeca Freecs" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 18117.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch APEX Season 4" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "GC Busan" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 91937.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9 KongDoo" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 14159.0);
SELECT id INTO @teamId FROM Team WHERE name = "RunAway" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 38514.0);
SELECT id INTO @teamId FROM Team WHERE name = "Nc Foxes" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10266.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch League - Inaugural Season" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "New York Excelsior" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 300000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Los Angeles Valiant" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 200000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Boston Uprising" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 150000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Los Angeles Gladiators" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 150000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Pacific Championship 2017 - Season 1" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Flash Wolves" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 98400.0);
SELECT id INTO @teamId FROM Team WHERE name = "ahq e-Sports Club" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 32800.0);
SELECT id INTO @teamId FROM Team WHERE name = "Hong Kong Attitude" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 26240.0);
SELECT id INTO @teamId FROM Team WHERE name = "Blank Esports" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 49200.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch APEX Season 3" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Lunatic-Hai" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 92707.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team KongDoo Panthera" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 38080.0);
SELECT id INTO @teamId FROM Team WHERE name = "AF.Blue" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 14222.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10861.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Premier Series 2017 - Spring" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "1246" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 36250.0);
SELECT id INTO @teamId FROM Team WHERE name = "LGD Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 18207.0);
SELECT id INTO @teamId FROM Team WHERE name = "Lucky Future" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 12138.0);
SELECT id INTO @teamId FROM Team WHERE name = "Oh My God" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 12138.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch APEX Season 2" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Lunatic-Hai" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 89910.0);
SELECT id INTO @teamId FROM Team WHERE name = "LW Blue" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 14856.0);
SELECT id INTO @teamId FROM Team WHERE name = "RunAway" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 37848.0);
SELECT id INTO @teamId FROM Team WHERE name = "Meta Athena" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 11098.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "APAC Premier 2016" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Rogue" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 75000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Lunatic-Hai" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 30000.0);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 22500.0);
SELECT id INTO @teamId FROM Team WHERE name = "NGA Club" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 22500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch APEX Season 1" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 87170.0);
SELECT id INTO @teamId FROM Team WHERE name = "BK Stars" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10618.0);
SELECT id INTO @teamId FROM Team WHERE name = "AF.Blue" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 35793.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team KongDoo Uncia" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10104.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch World Cup 2016" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Russia" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 18000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Finland" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 18000.0);
SELECT id INTO @teamId FROM Team WHERE name = "South Korea" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 18000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Sweden" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 18000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "2016 ESL Overwatch Atlantic Showdown - Gamescom" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Rogue" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 40000.0);
SELECT id INTO @teamId FROM Team WHERE name = "REUNITED" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 12000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 12000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Open" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Misfits" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 32000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 24000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Rogue" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 24000.0);
