SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2018 Season 3: Europe" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "TBA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "TBA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "TBA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Saudi Regional Tournament" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Osh-Tekk Warriors" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 160000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Inferno Game Zone" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 66667.0);
SELECT id INTO @teamId FROM Team WHERE name = "POWER eSport" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 40000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ricin" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2018 Season 3: Australia" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "TBA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "TBA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "TBA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "TBA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2018 Season 3: Pacific" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "TBA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "TBA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "TBA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "TBA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2018 Season 3: China" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "TBA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "TBA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "TBA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "TBA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2018 Season 3: North America" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "TBA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "TBA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "TBA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "TBA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2018 Season 3: Korea" and gameId=3;
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2018 Season 3: South America" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "TBA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "TBA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "TBA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "TBA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2018 Season 2: Europe" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Eagle Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 39555.5);
SELECT id INTO @teamId FROM Team WHERE name = "Angry Titans" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 23290.5);
SELECT id INTO @teamId FROM Team WHERE name = "Team Gigantti" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 18801.0);
SELECT id INTO @teamId FROM Team WHERE name = "Winstrike Team" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 17516.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "NetEase Esports X Tournament - Summer" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "RunAway" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 14625.0);
SELECT id INTO @teamId FROM Team WHERE name = "T1w Esports Club" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 8775.0);
SELECT id INTO @teamId FROM Team WHERE name = "LGD Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 4388.0);
SELECT id INTO @teamId FROM Team WHERE name = "LinGan e-Sports" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 1463.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2018 Season 2: Pacific" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Talon Esports" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 29764.0);
SELECT id INTO @teamId FROM Team WHERE name = "CYCLOPS athlete gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 17370.0);
SELECT id INTO @teamId FROM Team WHERE name = "Monster Shield KR" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 13712.0);
SELECT id INTO @teamId FROM Team WHERE name = "Xavier Esports" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 12752.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2018 Season 2: North America" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Fusion University" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 41226.0);
SELECT id INTO @teamId FROM Team WHERE name = "XL2 Academy" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 23162.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Envy" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 17259.0);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 17901.5);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2018 Season 2: South America" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Brasil Gaming House" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 10376.0);
SELECT id INTO @teamId FROM Team WHERE name = "Isurus Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 5794.0);
SELECT id INTO @teamId FROM Team WHERE name = "Looking For Org" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 4386.0);
SELECT id INTO @teamId FROM Team WHERE name = "RevoltZ e-Sports Club" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 4034.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2018 Season 2: China" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Lucky Future Zenith" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 41483.0);
SELECT id INTO @teamId FROM Team WHERE name = "LGD Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 21620.0);
SELECT id INTO @teamId FROM Team WHERE name = "T1w Esports Club" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 17773.0);
SELECT id INTO @teamId FROM Team WHERE name = "Flag Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 16745.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2018 Season 2: Australia" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Sydney Drop Bears" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 10440.0);
SELECT id INTO @teamId FROM Team WHERE name = "ORDER" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 4450.0);
SELECT id INTO @teamId FROM Team WHERE name = "Kanga Esports" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 4322.0);
SELECT id INTO @teamId FROM Team WHERE name = "Dark Sided" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 5858.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2018 Season 1: China" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Lucky Future Zenith" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 40840.5);
SELECT id INTO @teamId FROM Team WHERE name = "T1w Esports Club" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 17002.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team CC" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 17516.0);
SELECT id INTO @teamId FROM Team WHERE name = "LGD Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 23933.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2018 Season 2: Korea" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "RunAway" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 40712.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team KongDoo Panthera" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 22648.0);
SELECT id INTO @teamId FROM Team WHERE name = "Element Mystic" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 17387.5);
SELECT id INTO @teamId FROM Team WHERE name = "Meta Bellum" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 17002.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2018 Season 1: Australia" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Sydney Drop Bears" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 10184.0);
SELECT id INTO @teamId FROM Team WHERE name = "Masterminds GC" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 6018.0);
SELECT id INTO @teamId FROM Team WHERE name = "Dark Sided" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 4706.0);
SELECT id INTO @teamId FROM Team WHERE name = "Blank Blue" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 4578.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2018 Season 1: Europe" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "British Hurricane" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 40198.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Gigantti" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 21877.0);
SELECT id INTO @teamId FROM Team WHERE name = "CIS Hope" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 18030.0);
SELECT id INTO @teamId FROM Team WHERE name = "Angry Titans" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 18030.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2018 Season 1: North America" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Toronto Esports" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 23419.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fusion University" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 39684.0);
SELECT id INTO @teamId FROM Team WHERE name = "OpTic Academy" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 17644.5);
SELECT id INTO @teamId FROM Team WHERE name = "EnVision eSports" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 17516.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2018 Season 1: Korea" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "X6-Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 40198.0);
SELECT id INTO @teamId FROM Team WHERE name = "O2 Ardeont" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 21620.0);
SELECT id INTO @teamId FROM Team WHERE name = "RunAway" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 18544.0);
SELECT id INTO @teamId FROM Team WHERE name = "Meta Bellum" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 17002.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2018 Season 1: Pacific" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "DeToNator.KOREA" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 30916.0);
SELECT id INTO @teamId FROM Team WHERE name = "Blank Esports" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 17562.0);
SELECT id INTO @teamId FROM Team WHERE name = "Hong Kong Attitude" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 13328.0);
SELECT id INTO @teamId FROM Team WHERE name = "MEGA Esports" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 13040.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2018 Season 1: South America" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Brasil Gaming House" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 10248.0);
SELECT id INTO @teamId FROM Team WHERE name = "Isurus Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 5730.0);
SELECT id INTO @teamId FROM Team WHERE name = "paiN Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 4642.0);
SELECT id INTO @teamId FROM Team WHERE name = "Nocturns Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 4578.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Team Story - Chapter 4" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Meta Bellum" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team KongDoo Panthera" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "X6-Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "LGD Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Nexus Cup 2017 - Annual Finals" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "X6-Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 12116.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team KongDoo Panthera" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 6058.0);
SELECT id INTO @teamId FROM Team WHERE name = "Element Mystic" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 3029.0);
SELECT id INTO @teamId FROM Team WHERE name = "Lunatic-Hai" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 1515.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Seoul Cup - OGN Super Match" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Lunatic-Hai" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 60000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9 KongDoo" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Lucky Future" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Miraculous Youngster" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2017 Season 1: North America" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 40000.0);
SELECT id INTO @teamId FROM Team WHERE name = "EnVision eSports" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "FNRGFE" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2017 Season 1: Europe" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Team Gigantti" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 40000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9 EU" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "123" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Misfits" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 15000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2017 Season Zero: North America" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Immortals" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "FNRGFE" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 4000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Kungarna" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 4000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Team Story - Chapter 2" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Vici Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 21750.0);
SELECT id INTO @teamId FROM Team WHERE name = "Star Horn Royal Club" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 7250.0);
SELECT id INTO @teamId FROM Team WHERE name = "iG.Fire" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 14500.0);
SELECT id INTO @teamId FROM Team WHERE name = "LLG" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 7250.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Contenders 2017 Season Zero: Europe" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "eUnited" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Laser Kittenz" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 4000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Bazooka Puppiez" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 4000.0);
SELECT id INTO @teamId FROM Team WHERE name = "123" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch TaKeOver 2" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Rogue" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "eUnited" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 12500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 8500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Movistar Riders" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 4000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Rumble - April" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Rogue" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 6000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 3000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Selfless Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 1000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming Evil" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch PIT Championship - Europe Season 1" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Movistar Riders" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 6750.0);
SELECT id INTO @teamId FROM Team WHERE name = "Misfits" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 1800.0);
SELECT id INTO @teamId FROM Team WHERE name = "eUnited" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 3750.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 2700.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch PIT Championship - North America Season 1" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Rogue" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 6750.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 3750.0);
SELECT id INTO @teamId FROM Team WHERE name = "Selfless Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 2700.0);
SELECT id INTO @teamId FROM Team WHERE name = "Counter Logic Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 1800.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Oceanic Summer Series" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Fusion Girls" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 4600.0);
SELECT id INTO @teamId FROM Team WHERE name = "Scylla Esports" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 1534.0);
SELECT id INTO @teamId FROM Team WHERE name = "Just a Minute Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 767.0);
SELECT id INTO @teamId FROM Team WHERE name = "Love Shack" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 767.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Carbon Series" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Immortals" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 7500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming Evil" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 5000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Renegades" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 4000.0);
SELECT id INTO @teamId FROM Team WHERE name = "compLexity Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 3000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Winter Premiere" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Immortals" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 40000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ghost Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 12000.0);
SELECT id INTO @teamId FROM Team WHERE name = "compLexity Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 12000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Old Spice Tournament" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Black Dragons e-Sports" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 6260.0);
SELECT id INTO @teamId FROM Team WHERE name = "WS Esports" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 3913.0);
SELECT id INTO @teamId FROM Team WHERE name = "Keep Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 1565.0);
SELECT id INTO @teamId FROM Team WHERE name = "First e-Sports" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 1252.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Major League Gaming Vegas 2016" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 40000.0);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 12000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 12000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Intel Extreme Masters Season XI Gyeonggi" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "LW Red" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Lunatic-Hai" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "AF.Blue" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 12000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Rogue" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 12000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Team Story - Chapter 1" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Star Horn Royal Club" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 43550.0);
SELECT id INTO @teamId FROM Team WHERE name = "WE.White" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 21780.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Celestial" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 14520.0);
SELECT id INTO @teamId FROM Team WHERE name = "Newbee" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 7250.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Masters Gaming Arena 2016" and gameId=3;
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Winter 2016" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Misfits" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 30000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 5000.0);
SELECT id INTO @teamId FROM Team WHERE name = "compLexity Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Taiwan Hong Kong and Macao Open 2016" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Stay Frosty" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 38400.0);
SELECT id INTO @teamId FROM Team WHERE name = "ahq S" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 15360.0);
SELECT id INTO @teamId FROM Team WHERE name = "Doge" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 7680.0);
SELECT id INTO @teamId FROM Team WHERE name = "ahq e-Sports Club" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 7680.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "APAC Premier 2016 - Chinese Main Qualifier" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Team Skadi's Gift" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 22500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Vici Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 9000.0);
SELECT id INTO @teamId FROM Team WHERE name = "iG.Fire" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 4500.0);
SELECT id INTO @teamId FROM Team WHERE name = "All Strike Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 4500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Team Story - Chapter 3" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "LaoYinBi" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 21750.0);
SELECT id INTO @teamId FROM Team WHERE name = "JD-Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 14500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Moss Seven Club" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 7250.0);
SELECT id INTO @teamId FROM Team WHERE name = "P90" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 7250.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Universal Tournament 2016 - Summer" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "JHG.Gold" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 9000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Newbee" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 3600.0);
SELECT id INTO @teamId FROM Team WHERE name = "LinGan e-Sports" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 1800.0);
SELECT id INTO @teamId FROM Team WHERE name = "Gank" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 900.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "BTS Overwatch Cup" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 5000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 3500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 1500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Gold Series Overwatch League 2016 - Shanghai" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "iG.Fire" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 18000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Snake eSports" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 4500.0);
SELECT id INTO @teamId FROM Team WHERE name = "eStar Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 13500.0);
SELECT id INTO @teamId FROM Team WHERE name = "NGA Club" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 9000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "OG Invitational" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 7000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Northern Gaming Red" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 3000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Operation Breakout" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 7500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 4000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Rogue" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 2000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 750.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Agents Rising" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 5000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 3500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Gale Force eSports" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 1500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Colorado Clutch" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch World Cup 2018" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "South Korea" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 16000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Canada" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 16000.0);
SELECT id INTO @teamId FROM Team WHERE name = "United Kingdom" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 16000.0);
SELECT id INTO @teamId FROM Team WHERE name = "China" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 16000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch League - Inaugural Season Playoffs" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "London Spitfire" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 1000000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Los Angeles Valiant" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Philadelphia Fusion" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 400000.0);
SELECT id INTO @teamId FROM Team WHERE name = "New York Excelsior" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 100000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch World Cup 2017" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "South Korea" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 9000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Canada" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 9000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Sweden" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 9000.0);
SELECT id INTO @teamId FROM Team WHERE name = "France" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 9000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch League - Inaugural Season" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "New York Excelsior" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 300000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Los Angeles Valiant" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 200000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Boston Uprising" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 150000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Los Angeles Gladiators" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 150000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "APAC Premier 2017" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "GC Busan" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 105693.0);
SELECT id INTO @teamId FROM Team WHERE name = "RunAway" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 45294.0);
SELECT id INTO @teamId FROM Team WHERE name = "Miraculous Youngster" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 18117.0);
SELECT id INTO @teamId FROM Team WHERE name = "Afreeca Freecs" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 18117.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Pacific Championship 2017 - Season 2" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Ardeont" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 99320.0);
SELECT id INTO @teamId FROM Team WHERE name = "Flash Wolves" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 49660.0);
SELECT id INTO @teamId FROM Team WHERE name = "Blank Esports" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 33107.0);
SELECT id INTO @teamId FROM Team WHERE name = "Hong Kong Attitude" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 26489.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Premier Series 2017 - Summer" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Miraculous Youngster" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 45518.0);
SELECT id INTO @teamId FROM Team WHERE name = "Vici Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 22759.0);
SELECT id INTO @teamId FROM Team WHERE name = "Miracle Team One" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15172.0);
SELECT id INTO @teamId FROM Team WHERE name = "LGD Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 15172.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Premier Series 2017 - Grand Finals" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Miraculous Youngster" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 60690.0);
SELECT id INTO @teamId FROM Team WHERE name = "1246" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 30345.0);
SELECT id INTO @teamId FROM Team WHERE name = "Vici Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15172.0);
SELECT id INTO @teamId FROM Team WHERE name = "Miracle Team One" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch APEX Season 4" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "GC Busan" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 91937.0);
SELECT id INTO @teamId FROM Team WHERE name = "RunAway" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 38514.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9 KongDoo" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 14159.0);
SELECT id INTO @teamId FROM Team WHERE name = "Nc Foxes" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10266.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Pacific Championship 2017 - Season 1" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Flash Wolves" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 98400.0);
SELECT id INTO @teamId FROM Team WHERE name = "Blank Esports" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 49200.0);
SELECT id INTO @teamId FROM Team WHERE name = "Hong Kong Attitude" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 26240.0);
SELECT id INTO @teamId FROM Team WHERE name = "ahq e-Sports Club" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 32800.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch APEX Season 3" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Lunatic-Hai" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 92707.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team KongDoo Panthera" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 38080.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10861.0);
SELECT id INTO @teamId FROM Team WHERE name = "AF.Blue" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 14222.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Premier Series 2017 - Spring" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "1246" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 36250.0);
SELECT id INTO @teamId FROM Team WHERE name = "LGD Gaming" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 18207.0);
SELECT id INTO @teamId FROM Team WHERE name = "Lucky Future" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 12138.0);
SELECT id INTO @teamId FROM Team WHERE name = "Oh My God" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 12138.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "APAC Premier 2016" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Rogue" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 75000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Lunatic-Hai" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 30000.0);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 22500.0);
SELECT id INTO @teamId FROM Team WHERE name = "NGA Club" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 22500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch APEX Season 2" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Lunatic-Hai" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 89910.0);
SELECT id INTO @teamId FROM Team WHERE name = "RunAway" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 37848.0);
SELECT id INTO @teamId FROM Team WHERE name = "LW Blue" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 14856.0);
SELECT id INTO @teamId FROM Team WHERE name = "Meta Athena" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 11098.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch World Cup 2016" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "South Korea" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 18000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Russia" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 18000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Sweden" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 18000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Finland" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 18000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch APEX Season 1" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 87170.0);
SELECT id INTO @teamId FROM Team WHERE name = "AF.Blue" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 35793.0);
SELECT id INTO @teamId FROM Team WHERE name = "BK Stars" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10618.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team KongDoo Uncia" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10104.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "2016 ESL Overwatch Atlantic Showdown - Gamescom" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Rogue" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 40000.0);
SELECT id INTO @teamId FROM Team WHERE name = "REUNITED" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 12000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 12000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Overwatch Open" and gameId=3;
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 32000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 24000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Misfits" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Rogue" and gameId = 3;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 24000.0);
