INSERT INTO Team(gameId, name, country, region) VALUES (3, "Ardeont", "Korea", "Korea");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Flash Wolves", "Taiwan", "Taiwan");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Hong Kong Attitude", "Hong Kong Taiwan", "Taiwan");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Blank Esports", "Australia", "Oceania");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Miraculous Youngster", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "1246", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Vici Gaming", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Miracle Team One", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Team South Korea", "Korea", "Korea");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Team Canada", "Canada", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Team Sweden", "Sweden", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Team France", "France", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Team China", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Team United Kingdom", "United Kingdom", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "GC Busan", "South Korea", "Korea");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "RunAway", "South Korea", "Korea");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "LGD Gaming", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Cloud9 KongDoo", "Korea United States", "Korea");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Foxes", "South Korea", "Korea");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "ahq e-Sports Club", "Taiwan", "Taiwan");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Lunatic-Hai", "South Korea", "Korea");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Team KongDoo Panthera", "South Korea", "Korea");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Afreeca Freecs", "South Korea", "Korea");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Team Envy", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Lucky Future", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Oh My God", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Rogue", "United States France", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "NRG Esports", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Team Russia", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Team Finland", "Finland", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "BK Stars", "South Korea", "Korea");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Team Kongdoo Uncia", "South Korea", "Korea");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "LW Blue", "South Korea", "Korea");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Meta Athena", "South Korea", "Korea");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "REUNITED", "Denmark Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Fnatic", "United Kingdom United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (3, "Misfits", "United States", "Europe");
