steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'server/'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml', 'env.yaml']
    dir: 'server/'
timeout: '1600s'
