export const Countries = {
    "United Kingdom": "GBR",
    "UK": "GBR",
    "Afghanistan":"AFG",
    "Albania":"ALB",
    "Algeria":"DZA",
    "Angola":"AGO",
    "Antarctica":"ATA",
    "Argentina":"ARG",
    "Armenia":"ARM",
    "Australia":"AUS",
    "US": "USA",
    "England": "GBR",
    "Austria":"AUT",
    "Azerbaijan":"AZE",
    "Bangladesh":"BGD",
    "Belarus":"BLR",
    "Belgium":"BEL",
    "Belize":"BLZ",
    "Benin":"BEN",
    "Bhutan":"BTN",
    "Bolivia":"BOL",
    "Bosnia and Herzegovina":"BIH",
    "Botswana":"BWA",
    "Brazil":"BRA",
    "Brunei":"BRN",
    "Bulgaria":"BGR",
    "Burkina Faso":"BFA",
    "Burundi":"BDI",
    "Cambodia":"KHM",
    "Cameroon":"CMR",
    "Canada":"CAN",
    "Central African Republic":"CAF",
    "Chad":"TCD",
    "USA": "USA",
    "de": "DEU",
    "Chile":"CHL",
    "China":"CHN",
    "Colombia":"COL",
    "Costa Rica":"CRI",
    "South Korea": "KOR",
    "Croatia":"HRV",
    "Cuba":"CUB",
    "Cyprus":"CYP",
    "Czech Republic":"CZE",
    "Democratic Republic of the Congo":"COD",
    "Denmark":"DNK",
    "Djibouti":"DJI",
    "Dominican Republic":"DOM",
    "East Timor":"TLS",
    "Ecuador":"ECU",
    "Egypt":"EGY",
    "El Salvador":"SLV",
    "Equatorial Guinea":"GNQ",
    "Eritrea":"ERI",
    "Estonia":"EST",
    "Ethiopia":"ETH",
    "Europe":"GBR",
    "Falkland Islands":"FLK",
    "Fiji":"FJI",
    "Finland":"FIN",
    "France":"FRA",
    "French Guiana":"GUF",
    "French Southern and Antarctic Lands":"ATF",
    "Gabon":"GAB",
    "Gambia":"GMB",
    "Georgia":"GEO",
    "Germany":"DEU",
    "Ghana":"GHA",
    "Greece":"GRC",
    "Greenland":"GRL",
    "Guatemala":"GTM",
    "Guinea":"GIN",
    "Guinea Bissau":"GNB",
    "Guyana":"GUY",
    "Haiti":"HTI",
    "Honduras":"HND",
    "Hungary":"HUN",
    "Iceland":"ISL",
    "India":"IND",
    "Indonesia":"IDN",
    "Iran":"IRN",
    "Iraq":"IRQ",
    "Ireland":"IRL",
    "Israel":"ISR",
    "Italy":"ITA",
    "Ivory Coast":"CIV",
    "Jamaica":"JAM",
    "Japan":"JPN",
    "Jordan":"JOR",
    "Kazakhstan":"KAZ",
    "Kenya":"KEN",
    "Korea":"KOR",
    "Kosovo":"KOS",
    "Kuwait":"KWT",
    "Kyrgyzstan":"KGZ",
    "Hong Kong": "CHN",
    "Americas": "USA",
    "Oceania": "AUS",
    "Laos":"LAO",
    "Latvia":"LVA",
    "Lebanon":"LBN",
    "Lesotho":"LSO",
    "Liberia":"LBR",
    "Libya":"LBY",
    "Lithuania":"LTU",
    "Luxembourg":"LUX",
    "Macedonia":"MKD",
    "Madagascar":"MDG",
    "Malawi":"MWI",
    "Malaysia":"MYS",
    "Mali":"MLI",
    "Mauritania":"MRT",
    "Mexico":"MEX",
    "Moldova":"MDA",
    "Mongolia":"MNG",
    "Montenegro":"MNE",
    "Morocco":"MAR",
    "Mozambique":"MOZ",
    "Myanmar":"MMR",
    "Namibia":"NAM",
    "Nepal":"NPL",
    "Netherlands":"NLD",
    "New Caledonia":"NCL",
    "New Zealand":"NZL",
    "Nicaragua":"NIC",
    "Niger":"NER",
    "Nigeria":"NGA",
    "North Korea":"PRK",
    "Norway":"NOR",
    "Oman":"OMN",
    "Pakistan":"PAK",
    "Panama":"PAN",
    "Papua New Guinea":"PNG",
    "Paraguay":"PRY",
    "Peru":"PER",
    "Poland":"POL",
    "Portugal":"PRT",
    "Puerto Rico":"PRI",
    "Qatar":"QAT",
    "Republic of Serbia":"SRB",
    "Republic of the Congo":"COG",
    "Romania":"ROU",
    "Russia":"RUS",
    "Rwanda":"RWA",
    "Saudi Arabia":"SAU",
    "Senegal":"SEN",
    "Sierra Leone":"SLE",
    "Singapore":"PHL",
    "Philippines": "PHL",
    "North America": "CAN",
    "Slovakia":"SVK",
    "Slovenia":"SVN",
    "Solomon Islands":"SLB",
    "Somalia":"SOM",
    "South Africa":"ZAF",
    "South Sudan":"SSD",
    "Spain":"ESP",
    "Sri Lanka":"LKA",
    "Sudan":"SDN",
    "Suriname":"SUR",
    "Swaziland":"SWZ",
    "Sweden":"SWE",
    "Switzerland":"CHE",
    "Syria":"SYR",
    "Taiwan":"TWN",
    "Tajikistan":"TJK",
    "Thailand":"THA",
    "The Bahamas":"BHS",
    "Togo":"TGO",
    "Trinidad and Tobago":"TTO",
    "Tunisia":"TUN",
    "Turkey":"TUR",
    "Turkmenistan":"TKM",
    "Uganda":"UGA",
    "Ukraine":"UKR",
    "United Arab Emirates":"ARE",
    "United Republic of Tanzania":"TZA",
    "United States":"USA",
    "us": "USA",
    "Uruguay":"URY",
    "Uzbekistan":"UZB",
    "Vanuatu":"VUT",
    "Venezuela":"VEN",
    "Vietnam":"VNM",
    "West Bank":"PSE",
    "Western Sahara":"ESH",
    "Yemen":"YEM",
    "Zambia":"ZMB",
    "Zimbabwe":"ZWE"
};

export const countries_EU = [
    "Russia",
    "Ukraine",
    "France",
    "Spain",
    "Sweden",
    "Norway",
    "Germany",
    "Finland",
    "Poland",
    "Italy",
    "United Kingdom",
    "Romania",
    "Belarus",
    "Greece",
    "Bulgaria",
    "Iceland",
    "Hungary",
    "Portugal",
    "Austria",
    "Czech Republic",
    "Republic of Serbia",
    "Bosnia and Herzegovina",
    "Ireland",
    "Lithuania",
    "Latvia",
    "Croatia",
    "Slovakia",
    "Estonia",
    "Denmark",
    "Switzerland",
    "Netherlands",
    "Moldova",
    "Belgium",
    "Armenia",
    "Albania",
    "Macedonia",
    "Turkey",
    "Slovenia",
    "Montenegro",
    "Cyprus",
    "Luxembourg",
    "Andorra",
    "Malta",
    "Liechtenstein",
    "San Marino",
    "Monaco",
    "Kosovo"
];