INSERT INTO Team(gameId, name, country, region) VALUES (4, "Dignitas", "United Kingdom Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Method", "Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Cloud9", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "We Dem Girlz", "Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "CompLexity Gaming", "United States Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "G2 Esports", "Spain North America", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "NRG Esports", "United States North America", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Gale Force eSports", "United States", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Mock-It Esports", "North America", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Chiefs Esports Club", "Australia", "Oceania");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "PSG Esports", "France Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Evil Geniuses", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Renault Vitality", "France", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Team Envy", "United States Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "FlipSid3 Tactics", "United States Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Ghost Gaming", "United States North America", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Mock-It eSports EU", "Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Atelier", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "The Leftovers", "Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Northern Gaming", "Canada Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Take 3", "North America", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Selfless Gaming", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Genesis", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Denial Esports", "United States Canada", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Savage!", "Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Orbit eSports", "Sweden United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "iBUYPOWER", "United States North America", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "The Flying Dutchmen", "Netherlands", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Fnatic", "United Kingdom Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Splyce", "United States North America", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Precision Z", "Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Bread", "North America", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Rogue", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Allegiance", "North America", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "ORDER", "Australia", "Oceania");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Compadres", "North America", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Momentum", "North America", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Tainted Minds", "Australia", "Oceania");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "SYF Gaming", "Australia", "Oceania");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "The Peeps", "North America", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Team Secret", "Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "FlyQuest", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Sol eSports", "North America", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (4, "Upper 90 eSports", "United States North America", "North America");
