SELECT id INTO @tournamentId FROM Tournament WHERE name = "ELEAGUE Cup 2018: Rocket League" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 30000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Dignitas" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 15000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ELEAGUE Cup 2017: Rocket League" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 70000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Gale Force eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 30000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Mock-It eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 12000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 12000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 4 - Finals" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Gale Force eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 55000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Method" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 30000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 16000.0);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 11000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 5 - Finals" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 60000.0);
SELECT id INTO @teamId FROM Team WHERE name = "compLexity Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 30000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 15000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 6 - Finals" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 200000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Dignitas" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 120000.0);
SELECT id INTO @teamId FROM Team WHERE name = "We Dem Girlz" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 60000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Chiefs Esports Club" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 30000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 4 - Europe" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Gale Force eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 17250.0);
SELECT id INTO @teamId FROM Team WHERE name = "Method" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 13750.0);
SELECT id INTO @teamId FROM Team WHERE name = "Mock-It eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 11250.0);
SELECT id INTO @teamId FROM Team WHERE name = "PSG Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 9250.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 6 - North America" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 38531.25);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 33531.25);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 28531.25);
SELECT id INTO @teamId FROM Team WHERE name = "Evil Geniuses" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25531.25);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 5 - North America" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 20500.0);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 17000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 14500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Evil Geniuses" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 12500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 5 - Europe" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Gale Force eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 20500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Renault Vitality" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 17000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Envy" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 14500.0);
SELECT id INTO @teamId FROM Team WHERE name = "compLexity Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 12500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 6 - Europe" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 38531.25);
SELECT id INTO @teamId FROM Team WHERE name = "We Dem Girlz" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 33531.25);
SELECT id INTO @teamId FROM Team WHERE name = "FlipSid3 Tactics" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 28531.25);
SELECT id INTO @teamId FROM Team WHERE name = "PSG Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25531.25);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 4 - North America" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 17250.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ghost Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 13750.0);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 11250.0);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 9250.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 3 - Europe" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Mock-It eSports EU" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 13500.0);
SELECT id INTO @teamId FROM Team WHERE name = "FlipSid3 Tactics" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "The Leftovers" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 7500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Northern Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 2 - Finals" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "FlipSid3 Tactics" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Mock-It eSports EU" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Northern Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Take 3" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 3 - North America" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 13500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Atelier" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Selfless Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 7500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Denial Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 3 - Finals" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Northern Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 55000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Mock-It eSports EU" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 30000.0);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 16000.0);
SELECT id INTO @teamId FROM Team WHERE name = "The Leftovers" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 11000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 2 - North America" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "NRG eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 13500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Orbit eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Genesis" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 7500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Take 3" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 1 - Finals" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "iBUYPOWER" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 27500.0);
SELECT id INTO @teamId FROM Team WHERE name = "FlipSid3 Tactics" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 11000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Northern Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 4950.0);
SELECT id INTO @teamId FROM Team WHERE name = "The Flying Dutchmen" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 3850.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 2 - Europe" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "FlipSid3 Tactics" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 13500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Northern Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Mock-It eSports EU" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 7500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Precision Z" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 6 - Europe: Promotion Playoffs" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Red Reserve" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Savage!" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "compLexity Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 6 - North America: Promotion Playoffs" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Splyce" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Bread" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Rogue" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Allegiance" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Throwdown Esports: RLOC Season 6 - Finals" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Tainted Minds" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 12500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Chiefs Esports Club" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 9000.0);
SELECT id INTO @teamId FROM Team WHERE name = "ORDER" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 7000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SYF Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 6000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 6 - North America: RLRS" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Splyce" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 13000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Bread" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "The Peeps" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 7000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Compadres" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 6000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 6 - Europe: RLRS" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Savage!" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 13000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Red Reserve" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Method" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 7000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Secret" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 6000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Throwdown Esports: RLOC Season 6" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Chiefs Esports Club" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Tainted Minds" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "SYF Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "ORDER" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Rocket League Universal Open: Season 2 - US West Regionals" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Momentum" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 1500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Evil Geniuses Blue" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 1000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SizzleUrCob" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 500.0);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports B" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Rocket League Universal Open: Season 2" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 32500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Girls" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "compLexity Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ghost Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 8000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Rocket League Universal Open: Season 2 - US Central Regionals" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 1500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Sol eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 1000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Evil Geniuses" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ducks on Quack" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Rocket League Universal Open: Season 2 - US Northeast Regionals" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Ghost Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 1500.0);
SELECT id INTO @teamId FROM Team WHERE name = "FlyQuest" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 1000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Word" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Hockcat eGames" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Rocket League Universal Open: Season 2 - US East Regionals" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 1500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Sathstroh" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 1000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Upper 90 eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Splyce" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Gfinity Australia Elite Series - Season 1" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "ORDER" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 14848.0);
SELECT id INTO @teamId FROM Team WHERE name = "Avant Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 7424.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ground Zero Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 4640.0);
SELECT id INTO @teamId FROM Team WHERE name = "Chiefs Esports Club" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 4640.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Northern Arena: Rocket League Invitational 2" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 9000.0);
SELECT id INTO @teamId FROM Team WHERE name = "FlipSid3 Tactics" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 6400.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5200.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Rival Esports: The Climb - The Apex" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 3000.0);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 1500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Evil Geniuses" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 750.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ghost Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 5 - Europe: Promotion Playoffs" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Servette Geneva eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Secret" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "exceL Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 5 - North America: Promotion Playoffs" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "FlyQuest" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Allegiance" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Counter Logic Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Out of Style" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Gfinity United Kingdom Elite Series - Season 3" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Renault Vitality" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 34450.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Envy" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20670.0);
SELECT id INTO @teamId FROM Team WHERE name = "Method" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 6768.0);
SELECT id INTO @teamId FROM Team WHERE name = "Epsilon eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 6768.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Throwdown Esports: RLOC Season 5 - Finals" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Chiefs Esports Club" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 8250.0);
SELECT id INTO @teamId FROM Team WHERE name = "Tainted Minds" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 5000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Dark Sided" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 3750.0);
SELECT id INTO @teamId FROM Team WHERE name = "Legacy Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 2500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Throwdown Esports: RLOC Season 5" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Chiefs Esports Club" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Legacy Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Dark Sided" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Tainted Minds" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 5 - North America: RLRS" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "FlyQuest" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 6500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Allegiance" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 5000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Spacestation Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 3500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 3000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 5 - Europe: RLRS" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Team Secret" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 6500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Servette Geneva eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 5000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Placebo" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 3500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Triple Trouble" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 3000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Throwdown Esports: Open Series" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Chiefs Esports Club" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 3928.0);
SELECT id INTO @teamId FROM Team WHERE name = "Dark Sided" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 2749.0);
SELECT id INTO @teamId FROM Team WHERE name = "Legacy Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 1767.0);
SELECT id INTO @teamId FROM Team WHERE name = "Tainted Minds" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 1178.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Open Leipzig 2018" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "PSG Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 12000.0);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 6000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Guess Who" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 6000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL AU & NZ Championship: 2017 Season 3 Finals" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Chiefs Esports Club" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 3000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Pale Horse eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 2000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Dark Sided" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 1500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Scylla Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 1000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Gfinity United Kingdom Elite Series - Season 2" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Reason Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 26257.0);
SELECT id INTO @teamId FROM Team WHERE name = "Endpoint" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 13128.0);
SELECT id INTO @teamId FROM Team WHERE name = "Method" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 9190.0);
SELECT id INTO @teamId FROM Team WHERE name = "Prophecy" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 6564.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Throwdown Esports: RLOC Season 4 - Finals" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Chiefs Esports Club" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 8250.0);
SELECT id INTO @teamId FROM Team WHERE name = "Pale Horse eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 5000.0);
SELECT id INTO @teamId FROM Team WHERE name = "JAM Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 3750.0);
SELECT id INTO @teamId FROM Team WHERE name = "Scylla Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 2500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 4 - Europe: Promotion Playoffs" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Envy" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Secret" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "The Juicy Kids" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 4 - North America: Promotion Playoffs" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Renegades" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Out of Style" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Allegiance" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fibeon eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Northern Arena Rocket League Invitational" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 12000.0);
SELECT id INTO @teamId FROM Team WHERE name = "PSG Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 7500.0);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 4000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ghost Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 2500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Throwdown Esports: RLOC Season 4" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "JAM Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Chiefs Esports Club" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Pale Horse eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Scylla Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 4 - North America: RLRS" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Fibeon eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 6500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Out of Style" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 5000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Hammers" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 3500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ambition Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 3000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 4 - Europe: RLRS" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 6500.0);
SELECT id INTO @teamId FROM Team WHERE name = "The Juicy Kids" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 5000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Endpoint" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 3500.0);
SELECT id INTO @teamId FROM Team WHERE name = "ExRay" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 3000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Gfinity United Kingdom Elite Series - Season 1" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Endpoint" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 25810.0);
SELECT id INTO @teamId FROM Team WHERE name = "Epsilon eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 12905.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Infused" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 9190.0);
SELECT id INTO @teamId FROM Team WHERE name = "Method" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 6564.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Rocket League Universal Open: Season 1" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Gale Force eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 32500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Method" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SizzleUrCob" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Mock-It eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 7500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL AU & NZ Championship: 2017 Season 2 Finals" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Chiefs Esports Club" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 3000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Pale Horse eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 2000.0);
SELECT id INTO @teamId FROM Team WHERE name = "JAM Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 1500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Avant Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 1000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Summer 2017" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "FlipSid3 Tactics" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Gale Force eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 12000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Defusekids" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 6000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Rogue" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 6000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ThrowdownTV: Rocket League Challenge Season 3" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "JAM Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 2195.0);
SELECT id INTO @teamId FROM Team WHERE name = "Pale Horse eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 1520.1);
SELECT id INTO @teamId FROM Team WHERE name = "Scylla Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 1178.1);
SELECT id INTO @teamId FROM Team WHERE name = "Billy Fan Club" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 874.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "FACEIT X Games Rocket League Invitational" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 30000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Gale Force eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Selfless Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 7500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Envy" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 7500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Atlanta 2017" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "The Muffin Men" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Gale Force eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 12000.0);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 6000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Envy" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 6000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ThrowdownTV: Rocket League Challenge Season 2 - Finals" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Alpha Sydney" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 2908.81);
SELECT id INTO @teamId FROM Team WHERE name = "JAM Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 2237.55);
SELECT id INTO @teamId FROM Team WHERE name = "Sand Castle" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 1678.16);
SELECT id INTO @teamId FROM Team WHERE name = "1More" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 1006.9);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL AU & NZ Championship: 2017 Season 1 Finals" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Alpha Sydney" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 2400.0);
SELECT id INTO @teamId FROM Team WHERE name = "Corvidae" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 1600.0);
SELECT id INTO @teamId FROM Team WHERE name = "1More" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 1200.0);
SELECT id INTO @teamId FROM Team WHERE name = "Legacy eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 800.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ThrowdownTV: Rocket League Challenge Season 2" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Alpha Sydney" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "JAM Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Sand Castle" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "1More" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ThrowdownTV: Rocket League Challenge Season 1 - Finals" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Alpha Sydney" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 2500.0);
SELECT id INTO @teamId FROM Team WHERE name = "JAM Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 2000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Athletico" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 1500.0);
SELECT id INTO @teamId FROM Team WHERE name = "1More" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 1000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL PAX Australia 2016 Finals" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Legacy eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 2500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Abyss eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 1200.0);
SELECT id INTO @teamId FROM Team WHERE name = "Athletico" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 800.0);
SELECT id INTO @teamId FROM Team WHERE name = "Alpha Sydney" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 1 - Europe Qualifier 2" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "We Dem Girlz" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 3500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Supersonic Avengers" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 1500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Mock-It eSports EU" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "FlipSid3 Tactics" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLOC Season 1" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Nuovo Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 1667.16);
SELECT id INTO @teamId FROM Team WHERE name = "Gameroos XD" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 757.8);
SELECT id INTO @teamId FROM Team WHERE name = "Abyss eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 341.01);
SELECT id INTO @teamId FROM Team WHERE name = "Legacy eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 341.01);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 1 - Europe Qualifier 1" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "FlipSid3 Tactics" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 3500.0);
SELECT id INTO @teamId FROM Team WHERE name = "We Dem Girlz" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 1500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Mock-It eSports EU" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ka-Pow" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 1 - North America Qualifier 2" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Kings of Urban" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 3500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Exodus" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 1500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Lucky Bounce" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Genesis" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLCS Season 1 - North America Qualifier 1" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "iBUYPOWER" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 3500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Kings of Urban" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 1500.0);
SELECT id INTO @teamId FROM Team WHERE name = "VexX Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Genesis" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "RLC Pro League Season 1" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Crown & Jewels" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 2666.0);
SELECT id INTO @teamId FROM Team WHERE name = "FlipSid3 Tactics" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 1333.0);
SELECT id INTO @teamId FROM Team WHERE name = "iBUYPOWER" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 667.0);
SELECT id INTO @teamId FROM Team WHERE name = "Kings of Urban" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 667.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Major League Gaming Pro League - Season 1" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "FlipSid3 Tactics" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 1500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Swarm Gaming" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 750.0);
SELECT id INTO @teamId FROM Team WHERE name = "vQ Untethered" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 250.0);
SELECT id INTO @teamId FROM Team WHERE name = "Kings of Urban" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Rocet Circuit: Live Finals" and gameId=4;
SELECT id INTO @teamId FROM Team WHERE name = "Athletico" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 446.42);
SELECT id INTO @teamId FROM Team WHERE name = "Gameroos XD" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 186.01);
SELECT id INTO @teamId FROM Team WHERE name = "Legacy eSports" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 74.4);
SELECT id INTO @teamId FROM Team WHERE name = "Corvidae" and gameId = 4;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 37.2);
