INSERT INTO Team(gameId, name, country, region) VALUES (1, "VGJ.Storm", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Newbee", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Fnatic", "United Kingdom Malaysia", "Southeast Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "OG", "Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Virtus.pro", "Russia", "Commonwealth of Independent States");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "OpTic Gaming", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "paiN Gaming", "Brazil", "South America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Vici Gaming", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "PSG.LGD", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "FlyToMoon", "Russia", "Commonwealth of Independent States");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Evil Geniuses", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Liquid", "Netherlands Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Ninjas in Pyjamas", "Sweden Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "VGJ.Thunder", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Secret", "Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Mineski", "Philippines Malaysia", "Southeast Asia");
