INSERT INTO Team(gameId, name, country, region) VALUES (1, "VGJ.Storm", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Newbee", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Fnatic", "United Kingdom Malaysia", "Southeast Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Virtus.pro", "Russia", "Commonwealth of Independent States");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "OpTic Gaming", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Vici Gaming", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Secret", "Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "paiN Gaming", "Brazil", "South America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "PSG.LGD", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "OG", "Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Evil Geniuses", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "FlyToMoon", "Russia", "Commonwealth of Independent States");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Ninjas in Pyjamas", "Sweden Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Mineski", "Philippines Malaysia", "Southeast Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Liquid", "Netherlands Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "VGJ.Thunder", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "PSG.LGD", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "TNC Predator", "Philippines", "Southeast Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team NP", "Canada", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Natus Vincere", "Ukraine", "Commonwealth of Independent States");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "LGD.Forever Young", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Planet Odd", "Sweden", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "TNC Predator", "Philippines", "Southeast Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "mousesports", "Germany Greece", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Invictus Gaming", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Faceless", "Singapore", "Southeast Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Cloud9", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Infamous", "Peru", "South America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Alliance", "Sweden", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "iG Vitality", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "We Are Young", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Chaos", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "EHOME", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Wings Gaming", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "F.R.I.E.N.D.S.", "Russia", "Commonwealth of Independent States");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "VGJ.Thunder", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Prodota Gaming", "United Kingdom Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Ad Finem", "Greece", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "CDEC Youth", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Vega Squadron", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "MVP Phoenix", "South Korea", "Southeast Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Empire Faith", "Russia", "Commonwealth of Independent States");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "compLexity Gaming", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Vici Gaming Reborn", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "4 Clover & Lepricon", "Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "(monkey) Business", "Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "CDEC Gaming", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "London Conspiracy", "United Kingdom", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "TongFu.WanZhou", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "HellRaisers", "Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Malaysia", "Malaysia", "Southeast Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Burden United", "Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Tinker", "Canada", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "LV Gaming", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Sneaky Nyx Assassins", "USA", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Rave", "Philippines", "Southeast Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Big God", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "HyperGloryTeam", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Old Boys", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "ASUS Polar", "Russia", "Commonwealth of Independent States");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Zephyr", "South Korea", "Southeast Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Power Rangers", "Belarus", "Commonwealth of Independent States");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team DK", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Oslik Gaming", "Russia", "Commonwealth of Independent States");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "TongFu", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "MVP HOT6ix", "South Korea", "Southeast Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "5inQ", "$15", "674");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "StarTale", "South Korea", "Southeast Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Sigma", "France", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Eyes Of Tiger", "South Korea", "Southeast Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Eyes Of Tiger", "South Korea", "Southeast Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Speed Gaming.int", "Europe China", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Kaipi", "Romania", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Titan", "Malaysia", "Southeast Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "4 Friends + Chrillee", "Sweden", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "RoX", "Russia", "Commonwealth of Independent States");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "iNfernity Gaming", "Czech Republic", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "RisingStars", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "iCCup", "Russia", "Commonwealth of Independent States");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Quantic Gaming", "United States", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "MUFC", "Malaysia", "Southeast Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Dignitas", "United Kingdom", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Fnatic", "United Kingdom Malaysia", "Southeast Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Absolute Legends", "Belgium", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "No Tidehunter", "Sweden", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "LGD International", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Made in Thailand", "Thailand", "Southeast Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Pulse eSports", "United States", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Imaginary Gaming", "France", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Counter Logic Gaming", "United States", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "PotM Bottom", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Darer", "Bulgaria", "Commonwealth of Independent States");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Infused", "United Kingdom", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Moscow Five", "Russia", "Commonwealth of Independent States");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "mTw", "Germany", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Scythe Gaming", "Singapore", "Southeast Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Meet Your Makers", "Germany", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "Team Gamersleague", "Norway", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (1, "The Retry", "Russia", "Commonwealth of Independent States");
