INSERT INTO Team(gameId, name, country, region) VALUES (5, "Keyd Stars", "Brazil", "Brazil");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "KaBuM! e-Sports", "Brazil", "Brazil");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Kaos Latin Gamers", "Puerto Rico Chile", "South America");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Infinity eSports", "Costa Rica Mexico", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Flash Wolves", "Taiwan", "Taiwan");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "MAD Team", "Taiwan", "Taiwan");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "J Team", "Taiwan", "Taiwan");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Hong Kong Attitude", "Hong Kong", "Taiwan");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "SuperMassive eSports", "Turkey", "Turkey");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Royal Youth", "Turkey", "Turkey");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Team Just Alpha", "Russia", "CIS");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Gambit Esports", "United Kingdom Russia", "CIS");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "EVOS Esports", "Vietnam", "Vietnam");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "GAM Esports", "Vietnam", "Vietnam");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Vikings Gaming", "Vietnam", "Vietnam");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Fnatic", "United Kingdom Germany", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "G2 Esports", "Spain Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Team Liquid", "Netherlands United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Splyce", "United States Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "100 Thieves", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Echo Fox", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Royal Never Give Up", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Invictus Gaming", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "EDward Gaming", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Rogue Warriors", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "KT Rolster", "Korea", "Korea");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "SK Telecom T1", "Korea", "Korea");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "G-Rex", "Hong Kong Taiwan", "Taiwan");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Machi Esports", "Taiwan", "Taiwan");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Griffin", "Korea", "Korea");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Team Vitality", "France", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "FC Schalke 04 Esports", "Germany", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Misfits Gaming", "Germany Europe", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Team SoloMid", "United States World", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Cloud9", "United States North America", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "JD Gaming", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Dire Wolves", "Australia", "Oceania");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Chiefs Esports Club", "Australia", "Oceania");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "PENTAGRAM", "Japan", "Japan");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "DetonatioN FocusMe", "Japan", "Japan");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Unsold Stuff Gaming", "Japan", "Japan");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Legacy Esports", "Australia", "Oceania");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Ascension Gaming", "Thailand", "Southeast Asia");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Clutch Gaming", "United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "H2K", "United Kingdom United States", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Counter Logic Gaming", "United States North America", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Team Dignitas", "United Kingdom United States", "North America");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Samsung Galaxy", "Korea", "Korea");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Team WE", "China", "China");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Raise Gaming", "Taiwan", "Taiwan");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "1907 Fenerbahçe Esports", "Turkey", "Turkey");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Vega Squadron", "Russia CIS", "CIS");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "M19", "Russia", "CIS");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Virtus.pro", "Russia", "Europe");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "MVP", "Korea", "Korea");
INSERT INTO Team(gameId, name, country, region) VALUES (5, "Oh My God", "China", "China");
