SELECT id INTO @tournamentId FROM Tournament WHERE name = "Rift Rivals 2018: LLN vs CLS vs CBLOL" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "KaBuM! e-Sports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 12750.0);
SELECT id INTO @teamId FROM Team WHERE name = "Rebirth eSports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 8500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Kaos Latin Gamers" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 8500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Infinity eSports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 6, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Rainbow7" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 5, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "LMS Summer 2018" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Flash Wolves" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 48709.0);
SELECT id INTO @teamId FROM Team WHERE name = "MAD Team" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 19483.0);
SELECT id INTO @teamId FROM Team WHERE name = "J Team" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 12989.0);
SELECT id INTO @teamId FROM Team WHERE name = "Hong Kong Attitude" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 6494.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Rift Rivals 2018: LCL vs TCL vs VCS" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "SuperMassive eSports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 13000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Royal Bandits" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 13000.0);
SELECT id INTO @teamId FROM Team WHERE name = "RoX" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 5, 7000.0);
SELECT id INTO @teamId FROM Team WHERE name = "YouthCrew Esports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 13000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Just Alpha" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 6, 7000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Gambit Esports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 7000.0);
SELECT id INTO @teamId FROM Team WHERE name = "EVOS Esports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 8, 4000.0);
SELECT id INTO @teamId FROM Team WHERE name = "GIGABYTE Marines" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 7, 4000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Vikings Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 9, 4000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Rift Rivals 2018: NA vs EU" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Splyce" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "100 Thieves" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 5, 5000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Echo Fox" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 6, 5000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Rift Rivals 2018: LCK vs LPL vs LMS" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Royal Never Give Up" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Invictus Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "KING-ZONE DragonX" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 5, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "EDward Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Rogue Warriors" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Afreeca Freecs" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 6, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "KT Rolster" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 7, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Telecom T1" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 8, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Flash Wolves" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 9, 6000.0);
SELECT id INTO @teamId FROM Team WHERE name = "G-Rex" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 10, 6000.0);
SELECT id INTO @teamId FROM Team WHERE name = "MAD Team" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 11, 6000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Machi Esports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 12, 6000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "LCK Summer 2018" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "KT Rolster" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 88686.3);
SELECT id INTO @teamId FROM Team WHERE name = "Griffin" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 53211.78);
SELECT id INTO @teamId FROM Team WHERE name = "Afreeca Freecs" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 26605.89);
SELECT id INTO @teamId FROM Team WHERE name = "KING-ZONE DragonX" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 17737.26);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "EU LCS Summer 2018" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 92517.6);
SELECT id INTO @teamId FROM Team WHERE name = "Team Vitality" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 34694.1);
SELECT id INTO @teamId FROM Team WHERE name = "FC Schalke 04 Esports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 57823.5);
SELECT id INTO @teamId FROM Team WHERE name = "Misfits Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 23129.4);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "LPL Summer 2018" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Royal Never Give Up" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 218791.9);
SELECT id INTO @teamId FROM Team WHERE name = "Invictus Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 116689.02);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "NA LCS Summer 2018" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "LPL Summer 2018" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Rogue Warriors" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 43758.38);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "NA LCS Summer 2018" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 30000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "100 Thieves" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 20000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "LPL Summer 2018" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "JD Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 72930.63);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "2018 World Championship" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Invictus Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 834375.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 300375.0);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 155750.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 155750.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Rift Rivals 2018: SEA vs LJL vs OPL" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Dire Wolves" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Chiefs Esports Club" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Kuala Lumpur Hunters" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 5, 6000.0);
SELECT id INTO @teamId FROM Team WHERE name = "PENTAGRAM" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 7, 4000.0);
SELECT id INTO @teamId FROM Team WHERE name = "DetonatioN FocusMe" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 8, 4000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Unsold Stuff Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 9, 4000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Mineski" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 6, 6000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Legacy Esports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ascension Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 6000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "LPL Spring 2018" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Royal Never Give Up" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 237167.84);
SELECT id INTO @teamId FROM Team WHERE name = "Invictus Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 47433.57);
SELECT id INTO @teamId FROM Team WHERE name = "Rogue Warriors" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 79055.95);
SELECT id INTO @teamId FROM Team WHERE name = "EDward Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 126489.51);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "LMS Spring 2018" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Flash Wolves" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50849.46);
SELECT id INTO @teamId FROM Team WHERE name = "G-Rex" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20339.78);
SELECT id INTO @teamId FROM Team WHERE name = "MAD Team" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 13559.86);
SELECT id INTO @teamId FROM Team WHERE name = "Machi Esports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 6779.93);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Mid-Season Invitational 2018" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Royal Never Give Up" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 527650.2);
SELECT id INTO @teamId FROM Team WHERE name = "KING-ZONE DragonX" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 267251.4);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 133625.7);
SELECT id INTO @teamId FROM Team WHERE name = "Flash Wolves" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 133625.7);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "LCK Spring 2018" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "KING-ZONE DragonX" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 93798.0);
SELECT id INTO @teamId FROM Team WHERE name = "Afreeca Freecs" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 56279.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Telecom T1" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 18760.0);
SELECT id INTO @teamId FROM Team WHERE name = "KT Rolster" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 28139.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "NA LCS Spring 2018" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "100 Thieves" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Echo Fox" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 30000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Clutch Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 20000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "EU LCS Spring 2018" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 61437.0);
SELECT id INTO @teamId FROM Team WHERE name = "Splyce" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 36862.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Vitality" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 24575.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 98300.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "EU LCS Summer 2017" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 94400.0);
SELECT id INTO @teamId FROM Team WHERE name = "Misfits Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 59000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 35400.0);
SELECT id INTO @teamId FROM Team WHERE name = "H2K" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 23600.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "NA LCS Summer 2017" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Immortals" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Counter Logic Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 30000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 20000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "2017 World Championship" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Samsung Galaxy" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 1723721.63);
SELECT id INTO @teamId FROM Team WHERE name = "Royal Never Give Up" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 321761.37);
SELECT id INTO @teamId FROM Team WHERE name = "SK Telecom T1" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 620539.79);
SELECT id INTO @teamId FROM Team WHERE name = "Team WE" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 321761.37);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "LPL Summer 2017" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "EDward Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 217862.0);
SELECT id INTO @teamId FROM Team WHERE name = "Royal Never Give Up" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 116195.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team WE" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 43573.0);
SELECT id INTO @teamId FROM Team WHERE name = "Invictus Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 72621.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "LCK Summer 2017" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Longzhu Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 88553.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Telecom T1" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 53132.0);
SELECT id INTO @teamId FROM Team WHERE name = "KT Rolster" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 26566.0);
SELECT id INTO @teamId FROM Team WHERE name = "Samsung Galaxy" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 17711.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "LMS Summer 2017" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Flash Wolves" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 49287.0);
SELECT id INTO @teamId FROM Team WHERE name = "ahq e-Sports Club" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 19714.0);
SELECT id INTO @teamId FROM Team WHERE name = "Raise Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 13143.0);
SELECT id INTO @teamId FROM Team WHERE name = "J Team" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 6571.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Rift Rivals 2017: LCL vs TCL" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "SuperMassive eSports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "1907 Fenerbahçe Esports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team AURORA" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Crew e-Sports Club" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Vega Squadron" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 7, 5000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Vaevictis eSports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 6, 5000.0);
SELECT id INTO @teamId FROM Team WHERE name = "M19" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 8, 5000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 5, 5000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Rift Rivals 2017: LCK vs LPL vs LMS" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Team WE" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Royal Never Give Up" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "KT Rolster" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 6, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Samsung Galaxy" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 7, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "MVP" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 8, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Flash Wolves" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 9, 6000.0);
SELECT id INTO @teamId FROM Team WHERE name = "ahq e-Sports Club" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 10, 6000.0);
SELECT id INTO @teamId FROM Team WHERE name = "J Team" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 11, 6000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Machi Esports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 12, 6000.0);
SELECT id INTO @teamId FROM Team WHERE name = "EDward Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Oh My God" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Telecom T1" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 5, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Rift Rivals 2017: NA vs EU" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Phoenix1" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Unicorns Of Love" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 5, 5000.0);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 6, 5000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "LPL Spring 2017" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Royal Never Give Up" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 116162.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team WE" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 217805.0);
SELECT id INTO @teamId FROM Team WHERE name = "EDward Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 72602.0);
SELECT id INTO @teamId FROM Team WHERE name = "Oh My God" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 43561.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Mid-Season Invitational 2017" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "SK Telecom T1" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 676000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Flash Wolves" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 169000.0);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 338000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team WE" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 169000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "EU LCS Spring 2017" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 85600.0);
SELECT id INTO @teamId FROM Team WHERE name = "Unicorns Of Love" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 53500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 32100.0);
SELECT id INTO @teamId FROM Team WHERE name = "Misfits Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 21400.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "LMS Spring 2017" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Flash Wolves" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 49287.0);
SELECT id INTO @teamId FROM Team WHERE name = "ahq e-Sports Club" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 19714.0);
SELECT id INTO @teamId FROM Team WHERE name = "Machi Esports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 6571.0);
SELECT id INTO @teamId FROM Team WHERE name = "J Team" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 13143.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "NA LCS Spring 2017" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Phoenix1" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 30000.0);
SELECT id INTO @teamId FROM Team WHERE name = "FlyQuest" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "LCK Spring 2017" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "SK Telecom T1" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 89571.0);
SELECT id INTO @teamId FROM Team WHERE name = "Samsung Galaxy" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 26871.0);
SELECT id INTO @teamId FROM Team WHERE name = "KT Rolster" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 53743.0);
SELECT id INTO @teamId FROM Team WHERE name = "MVP" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 17914.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "IEM Season XI - World Championship" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Flash Wolves" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 70000.0);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 30000.0);
SELECT id INTO @teamId FROM Team WHERE name = "ROX Tigers" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "H2K" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 15000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "EU LCS Summer 2016" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Unicorns Of Love" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "H2K" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Splyce" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "NA LCS Summer 2016" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Immortals" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Counter Logic Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "LMS Summer 2016" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Flash Wolves" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 49287.0);
SELECT id INTO @teamId FROM Team WHERE name = "ahq e-Sports Club" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 13143.0);
SELECT id INTO @teamId FROM Team WHERE name = "J Team" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 19714.0);
SELECT id INTO @teamId FROM Team WHERE name = "Hong Kong Esports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 6571.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "2016 World Championship" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "SK Telecom T1" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 2028000.0);
SELECT id INTO @teamId FROM Team WHERE name = "H2K" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 380250.0);
SELECT id INTO @teamId FROM Team WHERE name = "Samsung Galaxy" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 760500.0);
SELECT id INTO @teamId FROM Team WHERE name = "ROX Tigers" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 380250.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "LCK Summer 2016" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "ROX Tigers" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 90200.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Telecom T1" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 27060.0);
SELECT id INTO @teamId FROM Team WHERE name = "KT Rolster" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 54120.0);
SELECT id INTO @teamId FROM Team WHERE name = "Samsung Galaxy" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 18040.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Mid-Season Invitational 2016" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "SK Telecom T1" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 250000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Counter Logic Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Royal Never Give Up" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Flash Wolves" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 50000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "LPL Spring 2016" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Royal Never Give Up" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 229500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team WE" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 76500.0);
SELECT id INTO @teamId FROM Team WHERE name = "EDward Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 122400.0);
SELECT id INTO @teamId FROM Team WHERE name = "QG Reapers" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 45900.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "LCK Spring 2016" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "SK Telecom T1" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 87800.0);
SELECT id INTO @teamId FROM Team WHERE name = "ROX Tigers" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 52680.0);
SELECT id INTO @teamId FROM Team WHERE name = "Jin Air Green Wings" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 17560.0);
SELECT id INTO @teamId FROM Team WHERE name = "KT Rolster" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 26340.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "NA LCS Spring 2016" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Counter Logic Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Immortals" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "EU LCS Spring 2016" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Origen" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "H2K" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "IEM Season X - World Championship" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "SK Telecom T1" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Royal Never Give Up" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "2015 World Championship" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "SK Telecom T1" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 1000000.0);
SELECT id INTO @teamId FROM Team WHERE name = "KOO Tigers" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 250000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Origen" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 150000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 150000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "LCK Summer 2015" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "SK Telecom T1" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 84793.0);
SELECT id INTO @teamId FROM Team WHERE name = "KOO Tigers" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25438.0);
SELECT id INTO @teamId FROM Team WHERE name = "CJ Entus" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 16959.0);
SELECT id INTO @teamId FROM Team WHERE name = "KT Rolster" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50876.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "NA LCS Summer 2015" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Counter Logic Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Impulse" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Mid Season Invitational 2015" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "EDward Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "ahq e-Sports Club" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Telecom T1" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "EU LCS Summer 2015" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Origen" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "H2K" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Unicorns Of Love" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "LCK Spring 2015" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "SK Telecom T1" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 92649.0);
SELECT id INTO @teamId FROM Team WHERE name = "CJ Entus" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 27795.0);
SELECT id INTO @teamId FROM Team WHERE name = "GE Tigers" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 55589.0);
SELECT id INTO @teamId FROM Team WHERE name = "Jin Air Green Wings" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 18530.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "NA LCS Spring 2015" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Impulse" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "EU LCS Spring 2015" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Unicorns Of Love" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "H2K" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "2014 World Championship" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Samsung White" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 1000000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Star Horn Royal Club" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 250000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Samsung Blue" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 150000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Oh My God" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 150000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "NA LCS Summer 2014" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "LMQ" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Curse" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "EU LCS Summer 2014" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Alliance" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team ROCCAT" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Champions Summer 2014" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "KT Rolster Arrows" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 78186.0);
SELECT id INTO @teamId FROM Team WHERE name = "Samsung Blue" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 39093.0);
SELECT id INTO @teamId FROM Team WHERE name = "Samsung White" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 23456.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Telecom T1 S" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 17592.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Champions Spring 2014" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Samsung Blue" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 74053.52);
SELECT id INTO @teamId FROM Team WHERE name = "NaJin White Shield" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 37026.76);
SELECT id INTO @teamId FROM Team WHERE name = "Samsung Ozone" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 22216.06);
SELECT id INTO @teamId FROM Team WHERE name = "CJ Entus Blaze" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 16662.04);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "NA LCS Spring 2014" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Counter Logic Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Curse" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "IEM Season VIII - World Championship" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "KT Rolster Bullets" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 60000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 30000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 14000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Gambit Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 14000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "EU LCS Spring 2014" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team ROCCAT" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Alliance" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Battle Of The Atlantic 2013" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Lemondogs" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Gambit Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team ALTERNATE" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 5, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 6, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 7, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "XDG Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 8, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 9, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Counter Logic Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 10, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Alliance" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Champions Summer 2013" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "SK Telecom T1 2" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 72078.57);
SELECT id INTO @teamId FROM Team WHERE name = "KT Rolster Bullets" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 36039.28);
SELECT id INTO @teamId FROM Team WHERE name = "CJ Entus Frost" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 16217.68);
SELECT id INTO @teamId FROM Team WHERE name = "MVP Ozone" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 21623.57);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Season 3 World Championship" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "SK Telecom T1" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 1000000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Royal Club" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 250000.0);
SELECT id INTO @teamId FROM Team WHERE name = "NaJin Black Sword" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 150000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 150000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "EU LCS Summer 2013" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Lemondogs" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Gambit Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Evil Geniuses" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Champions Spring 2013" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "MVP Ozone" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 70940.86);
SELECT id INTO @teamId FROM Team WHERE name = "CJ Entus Blaze" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 35470.43);
SELECT id INTO @teamId FROM Team WHERE name = "SK Telecom T1 2" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 21282.26);
SELECT id INTO @teamId FROM Team WHERE name = "CJ Entus Frost" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 15961.13);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "EU LCS Spring 2013" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Gambit Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Evil Geniuses" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "IEM Season VII - World Championship" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "CJ Entus Blaze" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "CJ Entus Frost" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Telecom T1 1" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 13500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Gambit Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 13500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "IGN Pro League Season 5" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Team WE" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Taipei Assassins" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 7500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Moscow Five" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 3000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Season 2 World Championship" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Taipei Assassins" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 1000000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Azubu Frost" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 250000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Moscow Five" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 150000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Counter Logic Gaming Europe" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 150000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "IEM Season VI - World Championship" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Moscow Five" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "against All authority" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 3800.0);
SELECT id INTO @teamId FROM Team WHERE name = "Counter Logic Gaming" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 8000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Riot Season 1 Championship" and gameId=5;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "against All authority" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Epik Gamer" and gameId = 5;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 7000.0);
