SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Masters Stockholm 2018" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "North" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 22000.0);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 22000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "EPICENTER 2018" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 150000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 75000.0);
SELECT id INTO @teamId FROM Team WHERE name = "AVANGAR" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 8000.0);
SELECT id INTO @teamId FROM Team WHERE name = "AVANGAR" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 3000.0);
SELECT id INTO @teamId FROM Team WHERE name = "5Power Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 1000.0);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 1000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 8 - Europe" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "BIG" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "North" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Esports Championship Series Season 6 - Finals" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 250000.0);
SELECT id INTO @teamId FROM Team WHERE name = "MIBR" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 120000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 65000.0);
SELECT id INTO @teamId FROM Team WHERE name = "North" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 65000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL One: New York 2018" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "mousesports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 125000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Gambit Esports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "StarSeries & i-League CS:GO Season 6" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "ENCE eSports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 125000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Vega Squadron" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "OpTic Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "FACEIT Major: London 2018" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 500000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 150000.0);
SELECT id INTO @teamId FROM Team WHERE name = "MIBR" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 70000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 70000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Intel Extreme Masters Season XIII - Chicago" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 42000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 20000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ELEAGUE CS:GO Premier 2018" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 500000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 200000.0);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 80000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 80000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL One: Belo Horizonte 2018" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 40000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 17000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 17000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL One: Cologne 2018" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 125000.0);
SELECT id INTO @teamId FROM Team WHERE name = "BIG" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 22000.0);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 22000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Esports Championship Series Season 5 - Finals" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 250000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 120000.0);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 65000.0);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 65000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 7 - Europe" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "mousesports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "StarSeries & i-League CS:GO Season 5" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 125000.0);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "North" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 7 - North America" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "OpTic Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Intel Extreme Masters Season XIII - Sydney" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 42000.0);
SELECT id INTO @teamId FROM Team WHERE name = "TYLOO" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 20000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Masters Marseille 2018" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Gambit Esports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 22000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 22000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 7 - Finals" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 250000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 110000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 55000.0);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 55000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "World Electronic Sports Games 2017" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 800000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Space Soldiers" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 300000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Russia" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 150000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team One" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 70000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Intel Extreme Masters Season XII - World Championship" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 250000.0);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 40000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 40000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Esports Championship Series Season 4 - Finals" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 250000.0);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 120000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 65000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 65000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 6: Finals" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 225000.0);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 60000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Misfits Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 60000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Intel Extreme Masters Season XII - Oakland" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 129000.0);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 54000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 28000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 28000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "StarLadder & i-League StarSeries Season 4" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "mousesports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 130000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 30000.0);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 15000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 6 - Europe" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "North" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 6 - North America" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "OpTic Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ELEAGUE Major: Boston 2018" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 500000.0);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 150000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 70000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 70000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "EPICENTER 2017" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 250000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 60000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 30000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESG Tour Mykonos 2017" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "mousesports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 120280.07);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 48112.31);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 24056.15);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 24056.15);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL One: New York 2017" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 125000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ELEAGUE CS:GO Premier 2017" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 500000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 150000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 70000.0);
SELECT id INTO @teamId FROM Team WHERE name = "North" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 70000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "PGL Major Kraków 2017" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Gambit Esports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 500000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Immortals" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 150000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 70000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 70000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL One: Cologne 2017" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 40000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 20000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Esports Championship Series Season 3 - Finals" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 250000.0);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 120000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 65000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 65000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Masters Malmö 2017" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "North" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Gambit Esports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 22000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 22000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 5: Finals" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 225000.0);
SELECT id INTO @teamId FROM Team WHERE name = "North" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 60000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 60000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 5 - Europe" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "North" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 5 - North America" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Immortals" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Intel Extreme Masters Season XII - Sydney" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 40000.0);
SELECT id INTO @teamId FROM Team WHERE name = "OpTic Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 20000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "StarLadder i-League StarSeries Season 3" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 125000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "HellRaisers" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Intel Extreme Masters Season XI World Championship" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 104000.0);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 44000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Immortals" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 24000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Heroic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 23000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ELEAGUE Season 2" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "OpTic Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 400000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 140000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 60000.0);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 60000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Masters Las Vegas 2017" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 200000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "North" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Intel Extreme Masters Season XI Oakland" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 128000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 53000.0);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 30000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 29000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Esports Championship Series Season 2 - Finals" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 250000.0);
SELECT id INTO @teamId FROM Team WHERE name = "OpTic Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 120000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 65000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 65000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "World Electronic Sports Games 2016" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 800000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Kinguin" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 400000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 200000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Space Soldiers" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 60000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ELEAGUE Major: Atlanta 2017" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 500000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 150000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 70000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 70000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Open Winter 2016" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Gambit Esports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Renegades" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "GODSENT" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Kinguin" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 4: Finals" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 200000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 90000.0);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 45000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 45000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "EPICENTER 2016" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 250000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 40000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 40000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 4 - North America" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Immortals" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "OpTic Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL One: New York 2016" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 125000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 4 - Europe" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "StarLadder i-League StarSeries Season 2" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 130000.0);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Open Bucharest 2016" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL One: Cologne 2016" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 500000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 150000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 70000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 70000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ELEAGUE Season 1" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 400000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 140000.0);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 70000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 60000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Esports Championship Series Season 1 - Finals" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 250000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 125000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 80000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 80000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Open Summer 2016" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Immortals" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "GODSENT" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "StarLadder i-League Invitational #1" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Dobry&Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 12000.0);
SELECT id INTO @teamId FROM Team WHERE name = "GODSENT" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 8000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "CEVO Pro League Season 9" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Tempo Storm" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 55000.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 30000.0);
SELECT id INTO @teamId FROM Team WHERE name = "HellRaisers" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 12500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 12500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 3 - North America" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "OpTic Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 3 - Europe" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 0.0);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 0.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Masters Malmö 2016" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 22000.0);
SELECT id INTO @teamId FROM Team WHERE name = "GODSENT" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 22000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "MLG Major Championship: Columbus 2016" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 500000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 150000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 70000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 70000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Intel Extreme Masters Season X World Championship" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 104000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 44000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 23000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Global eSports Cup - Season 1" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 80000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 30000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Counter Logic Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 20000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 3: Finals" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 200000.0);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 90000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 44000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 44000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Open Leipzig 2016" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "StarLadder i-League StarSeries XIV" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 90000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 40000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 20000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL ESEA Pro League Season 2: Finals" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 60000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Intel Extreme Masters Season X San Jose" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 56250.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 22500.0);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 11250.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 11250.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "FACEIT 2015 Stage 3 Finals at DreamHack Open Winter 2015" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL ESEA Pro League Season 2 - North America" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 18000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 16500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Conquest" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Counter Logic Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 13500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Fragbite Masters Season 5" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 26483.4);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 14713.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10593.4);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "iBUYPOWER Cup" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 65000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 5000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Counter Logic Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL ESEA Pro League Season 2 - Europe" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 18000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 16500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 13500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "CEVO Season 8 Professional" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 40000.0);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Titan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Conquest" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "The World Championships 2015" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "France" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Poland" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Sweden" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 7500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Russia" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 7500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "PGL CS:GO Championship Series Season 1: Finals" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 40000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Open Cluj-Napoca 2015" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 22000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 22000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Gfinity Champion of Champions" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 30000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Open London 2015" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 6000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 3000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Copenhagen Wolves" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 3000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL ESEA Pro League Invitational" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 60000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL One: Cologne 2015" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 22000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 22000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Intel Extreme Masters Season X - gamescom" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 45500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 16000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Renegades" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 6500.0);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "CEVO Season 7: Professional" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 30000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "FACEIT 2015 Stage 2 Finals at DreamHack Valencia 2015" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 40000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Electronic Sports World Cup 2015" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 30000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 8000.0);
SELECT id INTO @teamId FROM Team WHERE name = "FlipSid3 Tactics" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 8000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL ESEA Pro League Season 1 - Europe" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 18000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 16500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 13500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Gfinity Masters Summer 1" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 40000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 5000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL ESEA Pro League Season 1 Finals" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 60000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Counter Logic Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL ESEA Pro League Season 1 - North America" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 18000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Keyd Stars" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 16500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Counter Logic Gaming" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 13500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "StarLadder StarSeries XIII" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 22000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 12000.0);
SELECT id INTO @teamId FROM Team WHERE name = "GPlay.bg" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 5500.0);
SELECT id INTO @teamId FROM Team WHERE name = "FlipSid3 Tactics" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Open Summer 2015" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 6000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 3000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Titan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 3000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Gfinity Spring Masters 2" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 5000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Titan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Open Tours 2015" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 6000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 3000.0);
SELECT id INTO @teamId FROM Team WHERE name = "HellRaisers" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 3000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Fragbite Masters Season 4" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 26832.8);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 14907.1);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10733.1);
SELECT id INTO @teamId FROM Team WHERE name = "HellRaisers" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 7155.42);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 2981.43);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "PGL CS:GO Championship Series Kick-off Season" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 40000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "FACEIT League 2015 Stage I Finals" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 34000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 18000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 9500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 9500.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "StarLadder StarSeries XII" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 18000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 9000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 5000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Titan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 3000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESEA Season 18: Global Invite Division" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 70000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Titan" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Gfinity Spring Masters 1" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 15000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 7000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 3000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL One: Katowice 2015" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 22000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 22000.0);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "MLG X Games Aspen Invitational" and gameId=2;
SELECT id INTO @teamId FROM Team WHERE name = "Team LDLC.com" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 25000.0);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 12500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 7500.0);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic" and gameId = 2;
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5000.0);
