INSERT INTO Team(gameId, name, country, region) VALUES (2, "Heroic", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Copenhagen Wolves", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "MIBR", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "AVANGAR", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Sweden", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "France", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Counter Logic Gaming", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Cloud9", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "GPlay.bg", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "HellRaisers", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Fnatic", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "North", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Team Dignitas", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Russia", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Virtus.pro", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Titan", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Team Liquid", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Luminosity Gaming", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Dobry&Gaming", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Space Soldiers", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Team Kinguin", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "ENCE eSports", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "GODSENT", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "TYLOO", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "mousesports", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Team One", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "BIG", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Immortals", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Keyd Stars", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Team EnVyUs", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Team SoloMid", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Vega Squadron", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "FlipSid3 Tactics", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Tempo Storm", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Astralis", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Gambit Esports", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "OpTic Gaming", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "G2 Esports", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Poland", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Team LDLC.com", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Ninjas in Pyjamas", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Natus Vincere", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Renegades", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Conquest", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "FaZe Clan", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "SK Gaming", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "5Power Gaming", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "Misfits Gaming", "", "");
INSERT INTO Team(gameId, name, country, region) VALUES (2, "NRG Esports", "", "");
