INSERT INTO Team(name, country, region) VALUES ("Loveless", "United Arab Emirates", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Let's Do It", "Poland", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Gears of Destruction", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Team DileCom", "Peru", "South America");
INSERT INTO Team(name, country, region) VALUES ("Team Liquid", "Netherlands", "Europe");
INSERT INTO Team(name, country, region) VALUES ("FDL", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("Resurgence", "Singapore", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Team FanTuan", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Scratch the Surface", "Iraq", "Asia");
INSERT INTO Team(name, country, region) VALUES ("J.Storm", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("Cloud9", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("Thunderbirds", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("HAPPY GUYS", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("MidOrFeed", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Team OD", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Mineski", "Philippines", "Asia");
INSERT INTO Team(name, country, region) VALUES ("paiN X", "Brazil", "South America");
INSERT INTO Team(name, country, region) VALUES ("Sweden", "Sweden", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Prodota Gaming", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Team VGJ", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Kaipi", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Danish Bears", "Denmark", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Bravado Gaming", "South Africa", "Africa");
INSERT INTO Team(name, country, region) VALUES ("compLexity Gaming", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("PiTER", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("4Hate", "Singapore", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Union Gaming BO", "Bolivia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Wombat Gaming", "Germany", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Team Serenity", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("No Logic Gaming", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Moogle", "Singapore", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Newbee", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Intelligence Quotient", "Cambodia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Art of Execution", "Syria", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Da Teletubbies", "Australia", "Australia");
INSERT INTO Team(name, country, region) VALUES ("Denmark", "Denmark", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Monkey Freedom Fighters", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Orcus", "Jordan", "Asia");
INSERT INTO Team(name, country, region) VALUES ("United We Stand", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("HappyFeet", "Philippines", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Rock.Y", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("FlyToMoon", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Signify", "India", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Entity Gaming", "India", "Asia");
INSERT INTO Team(name, country, region) VALUES ("We Are Young", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("NecroRaisers", "Czech Republic", "Europe");
INSERT INTO Team(name, country, region) VALUES ("ANIMA.APACHE", "Russia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("ROOT Gaming", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("Top Team", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Zero Hoots Given", "Germany", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Excellent!", "France", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Immortals", "South Korea", "Asia");
INSERT INTO Team(name, country, region) VALUES ("URUK-HIGH", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Team Admiral", "Philippines", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Gersenz", "Mongolia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Void Boys", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("CDEC Avenger", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("United Kingdom", "United Kingdom", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Ten Twenty", "Singapore", "Asia");
INSERT INTO Team(name, country, region) VALUES ("4 Clover & Lepricon", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("STARK", "Germany", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Team Redemption", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Wings Gaming", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("EHOME.Keen", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Newbee Young", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Team Lithium", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Young Minds", "Philippines", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Team FIRE", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("Avalon Club", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("WU TANG", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("HellRaisers", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Clutch Gamers", "Philippines", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Fantastic Five", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Newteam123123", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Serbia", "Serbia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("5eva", "Singapore", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Raze", "Tunisia", "Africa");
INSERT INTO Team(name, country, region) VALUES ("Kings", "Iraq", "Asia");
INSERT INTO Team(name, country, region) VALUES ("ScaryFaceZ", "Ukraine", "Europe");
INSERT INTO Team(name, country, region) VALUES ("iClen", "Australia", "Australia");
INSERT INTO Team(name, country, region) VALUES ("Team 5ive", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Train your Brain", "Tunisia", "Africa");
INSERT INTO Team(name, country, region) VALUES ("MAX.X", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Digital Chaos", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("Team MAX", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("woof", "Netherlands", "Europe");
INSERT INTO Team(name, country, region) VALUES ("We Say NO!", "Sri Lanka", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Execration", "Philippines", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Psuedo Gaming", "Jordan", "Asia");
INSERT INTO Team(name, country, region) VALUES ("No Diggity", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Dream Gaming", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Vanguards", "Iran", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Midas Club Elite", "Brazil", "South America");
INSERT INTO Team(name, country, region) VALUES ("Can't Say Wips", "Australia", "Australia");
INSERT INTO Team(name, country, region) VALUES ("EVOS Esports", "Indonesia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("TNC Predator", "Philippines", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Quid Pro Quo", "Philippines", "Asia");
INSERT INTO Team(name, country, region) VALUES ("FATE eSports", "Jordan", "Asia");
INSERT INTO Team(name, country, region) VALUES ("White Rabbit Gaming", "South Africa", "Africa");
INSERT INTO Team(name, country, region) VALUES ("Royal Never Give Up", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Team Spirit", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("LGD Gaming", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Germany", "Germany", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Royal Bandits", "Turkey", "Asia");
INSERT INTO Team(name, country, region) VALUES ("TongFu", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Victory O Lord", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Underdogs", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("T Show", "Brazil", "South America");
INSERT INTO Team(name, country, region) VALUES ("Ultima_Thule", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Burden United", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("F.R.I.E.N.D.S.", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Rex Regum QEON", "Indonesia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Newbee.M", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("paiN Gaming", "Brazil", "South America");
INSERT INTO Team(name, country, region) VALUES ("Ad Finem", "Greece", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Finland", "Finland", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Butterfly Effect", "Spain", "Europe");
INSERT INTO Team(name, country, region) VALUES ("PRIES", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Team Malaysia", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Gambit Esports", "Russa", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Team X-BET", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("MOL", "Mongolia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Hashtag?.DOTA", "Thailand", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Longwan", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Elements One", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("SFTe-sports", "Russa", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Keen Gaming", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("BendOver", "Egypt", "Africa");
INSERT INTO Team(name, country, region) VALUES ("White Fries Gaming", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("NA Rejects", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("Insane Buster", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("SG e-sports", "Brazil", "South America");
INSERT INTO Team(name, country, region) VALUES ("Natus Vincere", "Ukraine", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Next Generation", "Vietnam", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Vega Squadron", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Five Libyans", "Libya", "Africa");
INSERT INTO Team(name, country, region) VALUES ("Life Breake", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Team Dogs Dota", "Jordan", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Team Tangos", "Sweden", "Europe");
INSERT INTO Team(name, country, region) VALUES ("VINCE TE IPSUM", "Brazil", "South America");
INSERT INTO Team(name, country, region) VALUES ("CIS Rejects", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("MVP HOT6ix", "South Korea", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Elite Wolves", "Peru", "South America");
INSERT INTO Team(name, country, region) VALUES ("Russia", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("TPB", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("VGJ.Thunder", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Team Aster", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("For The Dream", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Team eHug", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("Peru", "Peru", "South America");
INSERT INTO Team(name, country, region) VALUES ("Elements Pro", "Serbia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("CDEC Youth", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Team Faceless", "Singapore", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Rebirth eSports", "Chile", "South America");
INSERT INTO Team(name, country, region) VALUES ("KSY", "Australia", "Australia");
INSERT INTO Team(name, country, region) VALUES ("Power Gaming", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Hippomaniacs", "Czech Republic", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Without Problems", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("MVP Aegis", "South Korea", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Evil Geniuses", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("G Guard Esports", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Infamous", "Peru", "South America");
INSERT INTO Team(name, country, region) VALUES ("Baskonia eSports", "Spain", "Europe");
INSERT INTO Team(name, country, region) VALUES ("BPlease 420", "Morocco", "Africa");
INSERT INTO Team(name, country, region) VALUES ("Odium", "Ukraine", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Tigers", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Smash", "Saudi Arabia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("OpTic Gaming", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("AntiHype", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("2K Players", "United Arab Emirates", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Team Flash", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("LaFlamme", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Power Rangers", "Belarus", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Slayers", "Singapore", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Josskie", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("ROOONS", "Canada", "North America");
INSERT INTO Team(name, country, region) VALUES ("madjor atendari", "Bulgaria", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Brave Heart", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Geek Fam", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Rock", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("HOMETE", "South Korea", "Asia");
INSERT INTO Team(name, country, region) VALUES ("KnownFor", "Egypt", "Africa");
INSERT INTO Team(name, country, region) VALUES ("Team Leviathan", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("PSG.LGD", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("DeToNator", "Philippines", "Asia");
INSERT INTO Team(name, country, region) VALUES ("818 Esports", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Alliance", "Sweden", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Vici Gaming Reborn", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Fire Dragoon", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Team Secret", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Gremory Household", "Saudi Arabia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Wheel Whreck", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("FTD club C", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Basically Unknown", "Sweden", "Europe");
INSERT INTO Team(name, country, region) VALUES ("ANT E-Sports", "Turkey", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Forward Gaming", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("NoFear", "", "");
INSERT INTO Team(name, country, region) VALUES ("Big and Black", "Australia", "Australia");
INSERT INTO Team(name, country, region) VALUES ("TNC Pro Team", "Philippines", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Team Archon", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("Team Hellas", "Greece", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Nemiga Gaming", "Belarus", "Europe");
INSERT INTO Team(name, country, region) VALUES ("CDEC Gaming", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("4 Anchors + SC", "Finland", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Natural 9", "Australia", "Australia");
INSERT INTO Team(name, country, region) VALUES ("Doteri dva", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("MOBILE GIRL", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Golden Boys", "Peru", "South America");
INSERT INTO Team(name, country, region) VALUES ("UAshki", "Ukraine", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Zeta Pegasi", "Norway", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Orange.Taring", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("XENEX Gaming", "United Kingdom", "Europe");
INSERT INTO Team(name, country, region) VALUES ("VGJ.Storm", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("Team NP", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("NoLifer5.Reborn", "Kyrgyzstan", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Netherlands", "Netherlands", "Europe");
INSERT INTO Team(name, country, region) VALUES ("YAROST TOPORA", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Team Random", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Mad Dogs Team", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("LVLUP", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Team Lebanon", "Lebanon", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Not Today", "Peru", "South America");
INSERT INTO Team(name, country, region) VALUES ("MAX.Y", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Kingao+4", "Brazil", "South America");
INSERT INTO Team(name, country, region) VALUES ("Virtus.pro", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Lemondogs", "Sweden", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Mamas Boys", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("DVK", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("No Biggie", "Sweden", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Team Nation", "Australia", "Australia");
INSERT INTO Team(name, country, region) VALUES ("Invictus Gaming", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Team SatuDuaTiga", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Noobies in Team", "Morocco", "Asia");
INSERT INTO Team(name, country, region) VALUES ("InfinityVN", "Vietnam", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Team Kazakhstan", "Kazakhstan", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Electrify", "Singapore", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Comanche", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Fnatic", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Rave", "Philippines", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Bracerking", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Game of Throwz", "Kuwait", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Hollow", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Invasion e-Sports", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("EHOME.Luminous", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("NiceOne", "Kazakhstan", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Team Unknown", "Peru", "South America");
INSERT INTO Team(name, country, region) VALUES ("Ne RusЬ", "Ukraine", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Unchained Esports", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Team Albatross", "Poland", "Europe");
INSERT INTO Team(name, country, region) VALUES ("The Imperial", "Denmark", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Team YP", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("Planet Dog", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Winstrike Team", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("MVP Phoenix", "South Korea", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Balkan Bears", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Vici Gaming Potential", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Romania", "Romania", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Terror Blade !!", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Paragon eSports", "Belarus", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Team Singularity", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("NoPangolier", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("DUOBAO", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Learn2Gank", "Mexico", "North America");
INSERT INTO Team(name, country, region) VALUES ("RedBear", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Underminer", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("iG Vitality", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Planet Odd", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("FCDB Esports", "Belarus", "Europe");
INSERT INTO Team(name, country, region) VALUES ("HyperGloryTeam", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Vultur", "Argentina", "South America");
INSERT INTO Team(name, country, region) VALUES ("Volta7", "Ecuador", "South America");
INSERT INTO Team(name, country, region) VALUES ("ALPHA Red", "Thailand", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Thunder Awaken", "Peru", "South America");
INSERT INTO Team(name, country, region) VALUES ("mousesports", "Greece", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Team HighGround", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("ALTERNATE aTTaX", "Poland", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Dark Passage", "Turkey", "Asia");
INSERT INTO Team(name, country, region) VALUES ("PG.Barracx", "Indonesia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Tangerine", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Virtus.pro Polar", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Effect", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("G.star", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Team Empire", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Espada", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Slice N' Dice", "Egypt", "Africa");
INSERT INTO Team(name, country, region) VALUES ("Ukraine", "Ukraine", "Europe");
INSERT INTO Team(name, country, region) VALUES ("ferzee", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Summer's Rift", "USA", "North America");
INSERT INTO Team(name, country, region) VALUES ("Escape Gaming", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Big God", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Kabal Gaming", "Turkmenistan", "Asia");
INSERT INTO Team(name, country, region) VALUES ("LV Gaming", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("EHOME.X", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Que La Famille", "France", "Europe");
INSERT INTO Team(name, country, region) VALUES ("TongFu.WanZhou", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Vici Gaming", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Mineski.Sports5", "Philippines", "Asia");
INSERT INTO Team(name, country, region) VALUES ("ZOKEN GAMING", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("The Final Tribe", "Sweden", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Eximious Esports", "Pakistan", "Asia");
INSERT INTO Team(name, country, region) VALUES ("DUOBAO Young", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Seventh Heaven", "Australia", "Australia");
INSERT INTO Team(name, country, region) VALUES ("Team Kinguin", "Poland", "Europe");
INSERT INTO Team(name, country, region) VALUES ("PENTA Sports", "Europe", "");
INSERT INTO Team(name, country, region) VALUES ("The Mongolz", "Mongolia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Signature.Trust", "Thailand", "Asia");
INSERT INTO Team(name, country, region) VALUES ("iDeal eSports", "Thailand", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Arcade.PowerRangers", "Belarus", "Europe");
INSERT INTO Team(name, country, region) VALUES ("London Conspiracy", "Denmark", "Europe");
INSERT INTO Team(name, country, region) VALUES ("(monkey) Business", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Sacred", "Peru", "South America");
INSERT INTO Team(name, country, region) VALUES ("Game-Life Balance", "Czech Republic", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Team One Ecuador", "Ecuador", "South America");
INSERT INTO Team(name, country, region) VALUES ("OG", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("MVP Revolution", "Kyrgyzstan", "Asia");
INSERT INTO Team(name, country, region) VALUES ("90s Gaming", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("EHOME", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Team DK", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Aboshamalah", "Jordan", "Asia");
INSERT INTO Team(name, country, region) VALUES ("To.be.or.not.to.be", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Danish Dynamite", "Denmark", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Dad is Proud", "Algeria", "Africa");
INSERT INTO Team(name, country, region) VALUES ("Thunderobot Gaming", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Ice", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Azure esports", "Hong Kong", "Asia");
INSERT INTO Team(name, country, region) VALUES ("People", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Horde", "Sweden", "Europe");
INSERT INTO Team(name, country, region) VALUES ("ZERO ONE", "Kazakhstan", "Asia");
INSERT INTO Team(name, country, region) VALUES ("BOOM ID", "Singapore", "Asia");
INSERT INTO Team(name, country, region) VALUES ("WarriorsGaming.Unity", "Malaysia", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Ignore Ochir", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Play 4 Fun", "Canada", "North America");
INSERT INTO Team(name, country, region) VALUES ("Flipsid3 Tactics", "Russia", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Energy Pacemaker", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("mYinsanity", "", "Europe");
INSERT INTO Team(name, country, region) VALUES ("Immortal Magneto", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Team Anime", "Lebanon", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Speed Gaming.cn", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Aggressive 5", "India", "Asia");
INSERT INTO Team(name, country, region) VALUES ("s1 Lykos", "Philippines", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Ninjas in Pyjamas", "Sweden", "Europe");
INSERT INTO Team(name, country, region) VALUES ("LGD.Forever Young", "China", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Monsters Have Hearts", "Algeria", "Africa");
INSERT INTO Team(name, country, region) VALUES ("PUB PLAYERS", "Turkey", "Asia");
INSERT INTO Team(name, country, region) VALUES ("Team Tinker", "", "Europe");
