SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Masters Stockholm 2018";
SELECT id INTO @teamId FROM Team WHERE name = "North";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 22000);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 22000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "EPICENTER 2018";
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 150000);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 75000);
SELECT id INTO @teamId FROM Team WHERE name = "AVANGAR";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 20000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 20000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 8000);
SELECT id INTO @teamId FROM Team WHERE name = "AVANGAR";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 3000);
SELECT id INTO @teamId FROM Team WHERE name = "5Power Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 1000);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 1000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 8 - Europe";
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, -);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, -);
SELECT id INTO @teamId FROM Team WHERE name = "BIG";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, -);
SELECT id INTO @teamId FROM Team WHERE name = "North";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, -);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Esports Championship Series Season 6 - Finals";
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 250000);
SELECT id INTO @teamId FROM Team WHERE name = "MIBR";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 120000);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 65000);
SELECT id INTO @teamId FROM Team WHERE name = "North";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 65000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL One: New York 2018";
SELECT id INTO @teamId FROM Team WHERE name = "mousesports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 125000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000);
SELECT id INTO @teamId FROM Team WHERE name = "Gambit Esports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "StarSeries & i-League CS:GO Season 6";
SELECT id INTO @teamId FROM Team WHERE name = "ENCE eSports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 125000);
SELECT id INTO @teamId FROM Team WHERE name = "Vega Squadron";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "OpTic Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "FACEIT Major: London 2018";
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 500000);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 150000);
SELECT id INTO @teamId FROM Team WHERE name = "MIBR";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 70000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 70000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Intel Extreme Masters Season XIII - Chicago";
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 42000);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 20000);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 20000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ELEAGUE CS:GO Premier 2018";
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 500000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 200000);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 80000);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 80000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL One: Belo Horizonte 2018";
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 40000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 17000);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 17000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL One: Cologne 2018";
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 125000);
SELECT id INTO @teamId FROM Team WHERE name = "BIG";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 22000);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 22000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Esports Championship Series Season 5 - Finals";
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 250000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 120000);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 65000);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 65000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 7 - Europe";
SELECT id INTO @teamId FROM Team WHERE name = "mousesports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, -);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, -);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, -);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, -);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "StarSeries & i-League CS:GO Season 5";
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 125000);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000);
SELECT id INTO @teamId FROM Team WHERE name = "North";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 7 - North America";
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, -);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, -);
SELECT id INTO @teamId FROM Team WHERE name = "OpTic Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, -);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, -);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Intel Extreme Masters Season XIII - Sydney";
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 42000);
SELECT id INTO @teamId FROM Team WHERE name = "TYLOO";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 20000);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 20000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Masters Marseille 2018";
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "Gambit Esports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 22000);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 22000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 7 - Finals";
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 250000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 110000);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 55000);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 55000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "World Electronic Sports Games 2017";
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 800000);
SELECT id INTO @teamId FROM Team WHERE name = "Space Soldiers";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 300000);
SELECT id INTO @teamId FROM Team WHERE name = "Russia";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 150000);
SELECT id INTO @teamId FROM Team WHERE name = "Team One";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 70000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Intel Extreme Masters Season XII - World Championship";
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 250000);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 100000);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 40000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 40000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Esports Championship Series Season 4 - Finals";
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 250000);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 120000);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 65000);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 65000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 6: Finals";
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 225000);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 100000);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 60000);
SELECT id INTO @teamId FROM Team WHERE name = "Misfits Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 60000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Intel Extreme Masters Season XII - Oakland";
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 129000);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 54000);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 28000);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 28000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "StarLadder & i-League StarSeries Season 4";
SELECT id INTO @teamId FROM Team WHERE name = "mousesports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 130000);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 30000);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 15000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 6 - Europe";
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, -);
SELECT id INTO @teamId FROM Team WHERE name = "North";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, -);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, -);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, -);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 6 - North America";
SELECT id INTO @teamId FROM Team WHERE name = "OpTic Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, -);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, -);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, -);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, -);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ELEAGUE Major: Boston 2018";
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 500000);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 150000);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 70000);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 70000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "EPICENTER 2017";
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 250000);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 100000);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 60000);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 30000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESG Tour Mykonos 2017";
SELECT id INTO @teamId FROM Team WHERE name = "mousesports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 120280.07);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 48112.31);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 24056.15);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 24056.15);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL One: New York 2017";
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 125000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ELEAGUE CS:GO Premier 2017";
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 500000);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 150000);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 70000);
SELECT id INTO @teamId FROM Team WHERE name = "North";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 70000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "PGL Major Kraków 2017";
SELECT id INTO @teamId FROM Team WHERE name = "Gambit Esports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 500000);
SELECT id INTO @teamId FROM Team WHERE name = "Immortals";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 150000);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 70000);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 70000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL One: Cologne 2017";
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 40000);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 20000);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 20000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Esports Championship Series Season 3 - Finals";
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 250000);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 120000);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 65000);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 65000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Masters Malmö 2017";
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000);
SELECT id INTO @teamId FROM Team WHERE name = "North";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "Gambit Esports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 22000);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 22000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 5: Finals";
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 225000);
SELECT id INTO @teamId FROM Team WHERE name = "North";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 100000);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 60000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 60000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 5 - Europe";
SELECT id INTO @teamId FROM Team WHERE name = "North";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, -);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, -);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, -);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, -);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 5 - North America";
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, -);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, -);
SELECT id INTO @teamId FROM Team WHERE name = "Immortals";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, -);
SELECT id INTO @teamId FROM Team WHERE name = "NRG Esports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, -);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Intel Extreme Masters Season XII - Sydney";
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 40000);
SELECT id INTO @teamId FROM Team WHERE name = "OpTic Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 20000);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 20000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "StarLadder i-League StarSeries Season 3";
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 125000);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "HellRaisers";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Intel Extreme Masters Season XI World Championship";
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 104000);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 44000);
SELECT id INTO @teamId FROM Team WHERE name = "Immortals";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 24000);
SELECT id INTO @teamId FROM Team WHERE name = "Heroic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 23000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ELEAGUE Season 2";
SELECT id INTO @teamId FROM Team WHERE name = "OpTic Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 400000);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 140000);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 60000);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 60000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Masters Las Vegas 2017";
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 200000);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 100000);
SELECT id INTO @teamId FROM Team WHERE name = "North";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Intel Extreme Masters Season XI Oakland";
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 128000);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 53000);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 30000);
SELECT id INTO @teamId FROM Team WHERE name = "$29000";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4,  Astralis);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Esports Championship Series Season 2 - Finals";
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 250000);
SELECT id INTO @teamId FROM Team WHERE name = "OpTic Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 120000);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 65000);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 65000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "World Electronic Sports Games 2016";
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 800000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Kinguin";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 400000);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 200000);
SELECT id INTO @teamId FROM Team WHERE name = "Space Soldiers";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 60000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ELEAGUE Major: Atlanta 2017";
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 500000);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 150000);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 70000);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 70000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Open Winter 2016";
SELECT id INTO @teamId FROM Team WHERE name = "Gambit Esports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "Renegades";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000);
SELECT id INTO @teamId FROM Team WHERE name = "GODSENT";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Kinguin";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 4: Finals";
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 200000);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 90000);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 45000);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 45000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "EPICENTER 2016";
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 250000);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 100000);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 40000);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 40000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 4 - North America";
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, -);
SELECT id INTO @teamId FROM Team WHERE name = "Immortals";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, -);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, -);
SELECT id INTO @teamId FROM Team WHERE name = "OpTic Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, -);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL One: New York 2016";
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 125000);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 4 - Europe";
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, -);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, -);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, -);
SELECT id INTO @teamId FROM Team WHERE name = "FaZe Clan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, -);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "StarLadder i-League StarSeries Season 2";
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 130000);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Open Bucharest 2016";
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL One: Cologne 2016";
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 500000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 150000);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 70000);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 70000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ELEAGUE Season 1";
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 400000);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 140000);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 70000);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 60000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Esports Championship Series Season 1 - Finals";
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 250000);
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 125000);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 80000);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 80000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Open Summer 2016";
SELECT id INTO @teamId FROM Team WHERE name = "Immortals";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000);
SELECT id INTO @teamId FROM Team WHERE name = "GODSENT";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "StarLadder i-League Invitational #1";
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000);
SELECT id INTO @teamId FROM Team WHERE name = "Dobry&Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 12000);
SELECT id INTO @teamId FROM Team WHERE name = "GODSENT";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 8000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "CEVO Pro League Season 9";
SELECT id INTO @teamId FROM Team WHERE name = "Tempo Storm";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 55000);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 30000);
SELECT id INTO @teamId FROM Team WHERE name = "HellRaisers";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 12500);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 12500);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 3 - North America";
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, -);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, -);
SELECT id INTO @teamId FROM Team WHERE name = "OpTic Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, -);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, -);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 3 - Europe";
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, -);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, -);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, -);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, -);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Masters Malmö 2016";
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 22000);
SELECT id INTO @teamId FROM Team WHERE name = "GODSENT";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 22000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "MLG Major Championship: Columbus 2016";
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 500000);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 150000);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 70000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 70000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Intel Extreme Masters Season X World Championship";
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 104000);
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 44000);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 23000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Global eSports Cup - Season 1";
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 80000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 30000);
SELECT id INTO @teamId FROM Team WHERE name = "Counter Logic Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 20000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL Pro League Season 3: Finals";
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 200000);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 90000);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 44000);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 44000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Open Leipzig 2016";
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000);
SELECT id INTO @teamId FROM Team WHERE name = "Astralis";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "StarLadder i-League StarSeries XIV";
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 90000);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 40000);
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 20000);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 20000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL ESEA Pro League Season 2: Finals";
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 60000);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000);
SELECT id INTO @teamId FROM Team WHERE name = "?";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Intel Extreme Masters Season X San Jose";
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 56250);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 22500);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 11250);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 11250);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "FACEIT 2015 Stage 3 Finals at DreamHack Open Winter 2015";
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000);
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL ESEA Pro League Season 2 - North America";
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 18000);
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 16500);
SELECT id INTO @teamId FROM Team WHERE name = "Conquest";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000);
SELECT id INTO @teamId FROM Team WHERE name = "Counter Logic Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 13500);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Fragbite Masters Season 5";
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 26483.4);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 14713.0);
SELECT id INTO @teamId FROM Team WHERE name = "SK Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10593.40);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "iBUYPOWER Cup";
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 65000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000);
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 5000);
SELECT id INTO @teamId FROM Team WHERE name = "Counter Logic Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL ESEA Pro League Season 2 - Europe";
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 18000);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 16500);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 13500);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "CEVO Season 8 Professional";
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 40000);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000);
SELECT id INTO @teamId FROM Team WHERE name = "Titan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000);
SELECT id INTO @teamId FROM Team WHERE name = "Conquest";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "The World Championships 2015";
SELECT id INTO @teamId FROM Team WHERE name = "France";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "Poland";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000);
SELECT id INTO @teamId FROM Team WHERE name = "Sweden";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 7500);
SELECT id INTO @teamId FROM Team WHERE name = "Russia";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 7500);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "PGL CS:GO Championship Series Season 1: Finals";
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 40000);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Liquid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Open Cluj-Napoca 2015";
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "G2 Esports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 22000);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 22000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Gfinity Champion of Champions";
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 30000);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Open London 2015";
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 20000);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 6000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 3000);
SELECT id INTO @teamId FROM Team WHERE name = "Copenhagen Wolves";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 3000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL ESEA Pro League Invitational";
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 60000);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL One: Cologne 2015";
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 22000);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 22000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Intel Extreme Masters Season X - gamescom";
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 45500);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 16000);
SELECT id INTO @teamId FROM Team WHERE name = "Renegades";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 6500);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5500);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "CEVO Season 7: Professional";
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 30000);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 15000);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "FACEIT 2015 Stage 2 Finals at DreamHack Valencia 2015";
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 40000);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Electronic Sports World Cup 2015";
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 30000);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 15000);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 8000);
SELECT id INTO @teamId FROM Team WHERE name = "FlipSid3 Tactics";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 8000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL ESEA Pro League Season 1 - Europe";
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 18000);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 16500);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 13500);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Gfinity Masters Summer 1";
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 40000);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 5000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL ESEA Pro League Season 1 Finals";
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 60000);
SELECT id INTO @teamId FROM Team WHERE name = "Counter Logic Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 25000);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 25000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL ESEA Pro League Season 1 - North America";
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 18000);
SELECT id INTO @teamId FROM Team WHERE name = "Keyd Stars";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 16500);
SELECT id INTO @teamId FROM Team WHERE name = "Luminosity Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000);
SELECT id INTO @teamId FROM Team WHERE name = "Counter Logic Gaming";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 13500);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "StarLadder StarSeries XIII";
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 22000);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 12000);
SELECT id INTO @teamId FROM Team WHERE name = "GPlay.bg";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 5500);
SELECT id INTO @teamId FROM Team WHERE name = "FlipSid3 Tactics";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5500);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Open Summer 2015";
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 20000);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 6000);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 3000);
SELECT id INTO @teamId FROM Team WHERE name = "Titan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 3000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Gfinity Spring Masters 2";
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 25000);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 15000);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 5000);
SELECT id INTO @teamId FROM Team WHERE name = "Titan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "DreamHack Open Tours 2015";
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 20000);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 6000);
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 3000);
SELECT id INTO @teamId FROM Team WHERE name = "HellRaisers";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 3000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Fragbite Masters Season 4";
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 26832.80);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 14907.10);
SELECT id INTO @teamId FROM Team WHERE name = "9 Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10733.10);
SELECT id INTO @teamId FROM Team WHERE name = "HellRaisers";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 7155.42);
SELECT id INTO @teamId FROM Team WHERE name = "Natus Vincere";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 2981.43);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "PGL CS:GO Championship Series Kick-off Season";
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 40000);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 20000);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 10000);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "FACEIT League 2015 Stage I Finals";
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 34000);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 18000);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 9500);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 9500);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "StarLadder StarSeries XII";
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 18000);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 9000);
SELECT id INTO @teamId FROM Team WHERE name = "Team SoloMid";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 5000);
SELECT id INTO @teamId FROM Team WHERE name = "Titan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 3000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESEA Season 18: Global Invite Division";
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 70000);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 25000);
SELECT id INTO @teamId FROM Team WHERE name = "Titan";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 15000);
SELECT id INTO @teamId FROM Team WHERE name = "mousesports";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 10000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "Gfinity Spring Masters 1";
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 25000);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 15000);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 7000);
SELECT id INTO @teamId FROM Team WHERE name = "Cloud9";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 3000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "ESL One: Katowice 2015";
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 100000);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 50000);
SELECT id INTO @teamId FROM Team WHERE name = "Virtus.pro";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 22000);
SELECT id INTO @teamId FROM Team WHERE name = "Team EnVyUs";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 22000);
SELECT id INTO @tournamentId FROM Tournament WHERE name = "MLG X Games Aspen Invitational";
SELECT id INTO @teamId FROM Team WHERE name = "Team LDLC.com";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 1, 25000);
SELECT id INTO @teamId FROM Team WHERE name = "Ninjas in Pyjamas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 2, 12500);
SELECT id INTO @teamId FROM Team WHERE name = "Team Dignitas";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 3, 7500);
SELECT id INTO @teamId FROM Team WHERE name = "Fnatic";
INSERT INTO TournamentTeamRanking(tournamentId, teamId, teamRank, earning) VALUES (@tournamentId, @teamId, 4, 5000);
